import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { useLanguage } from '@/contexts/LanguageContext';
import CompositionEditor from './CompositionEditor';

interface CatalogItem {
  id: string;
  code: string;
  color_name: string;
  description: string | null;
  lastro_sku_code: string;
  logo_sku_code: string | null;
  status: string;
  type: string;
  composition: any[];
  weaving_knitted: string | null;
  fabric_type: string | null;
  weight_g_m2: number | null;
  produced_unit: string;
  sold_unit: string;
  eu_origin: boolean;
  sustainable_notes: string | null;
  product_notes: string | null;
  care_instructions: string | null;
  dyeing_batch_size: number | null;
}

interface CatalogOverviewTabProps {
  item: CatalogItem;
  onChange: (updates: Partial<CatalogItem>) => void;
  canEdit: boolean;
  isNew: boolean;
}

const TYPE_OPTIONS = [
  { value: 'lining', label: 'Lining' },
  { value: 'pocketing', label: 'Pocketing' },
  { value: 'sleeve_lining', label: 'Sleeve Lining' },
  { value: 'stretch', label: 'Stretch' },
  { value: 'knee_lining', label: 'Knee Lining' },
];

const UNIT_OPTIONS = [
  { value: 'meters', label: 'Meters' },
  { value: 'kilograms', label: 'Kilograms' },
];

const WEAVING_OPTIONS = [
  'taffeta', 'knitted', 'knitted chiffon', 'voile cotton', 'voile', 'twill',
  'herringbone', 'jacquard', 'satin', 'prestige', 'mech stretch', 'rhadame',
  'grosgrain', 'taffeta ponge', 'combined', 'georgette', 'dobby', 'twill changean',
  'weft black', 'changean rhadame', 'soft pongee dull', 'soft pongee', 'heavy taffeta',
  'greige', 'luxury taffeta', 'light satin', 'soft twill', 'stretch', 'stretch stripes',
  'lighter satin', 'soft rhadame twill', 'rhadame twill', 'pongee', 'poly dobby'
];

const CatalogOverviewTab: React.FC<CatalogOverviewTabProps> = ({
  item,
  onChange,
  canEdit,
  isNew,
}) => {
  const { t } = useLanguage();

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      {/* Basic Information */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">{t('catalog.basicInfo')}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="code">{t('catalog.qualityCode')} *</Label>
              <Input
                id="code"
                value={item.code}
                onChange={(e) => onChange({ code: e.target.value })}
                disabled={!canEdit}
                placeholder="e.g., P200"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="color_name">{t('catalog.colorName')} *</Label>
              <Input
                id="color_name"
                value={item.color_name}
                onChange={(e) => onChange({ color_name: e.target.value })}
                disabled={!canEdit}
                placeholder="e.g., Navy Blue"
              />
            </div>
          </div>

          {!isNew && (
            <div className="space-y-2">
              <Label>{t('catalog.ltaSku')}</Label>
              <div className="flex items-center gap-2">
                <Badge variant="outline" className="font-mono">
                  {item.lastro_sku_code}
                </Badge>
                <span className="text-xs text-muted-foreground">{t('catalog.autoGenerated')}</span>
              </div>
            </div>
          )}

          <div className="space-y-2">
            <Label htmlFor="logo_sku_code">{t('catalog.logoSku')}</Label>
            <Input
              id="logo_sku_code"
              value={item.logo_sku_code || ''}
              onChange={(e) => onChange({ logo_sku_code: e.target.value || null })}
              disabled={!canEdit}
              placeholder="Customer's SKU code"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="type">{t('catalog.type')}</Label>
            <Select
              value={item.type}
              onValueChange={(value) => onChange({ type: value })}
              disabled={!canEdit}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {TYPE_OPTIONS.map(opt => (
                  <SelectItem key={opt.value} value={opt.value}>
                    {opt.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">{t('catalog.description')}</Label>
            <Textarea
              id="description"
              value={item.description || ''}
              onChange={(e) => onChange({ description: e.target.value || null })}
              disabled={!canEdit}
              rows={3}
              placeholder="Product description..."
            />
          </div>
        </CardContent>
      </Card>

      {/* Fabric Properties */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">{t('catalog.fabricProperties')}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label>{t('catalog.composition')}</Label>
            <CompositionEditor
              composition={item.composition || []}
              onChange={(comp) => onChange({ composition: comp })}
              disabled={!canEdit}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="weaving_knitted">{t('catalog.construction')}</Label>
            <Select
              value={item.weaving_knitted || ''}
              onValueChange={(value) => onChange({ weaving_knitted: value || null })}
              disabled={!canEdit}
            >
              <SelectTrigger>
                <SelectValue placeholder={t('catalog.selectConstruction')} />
              </SelectTrigger>
              <SelectContent>
                {WEAVING_OPTIONS.map(opt => (
                  <SelectItem key={opt} value={opt}>
                    {opt.charAt(0).toUpperCase() + opt.slice(1)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="weight_g_m2">{t('catalog.weight')}</Label>
              <Input
                id="weight_g_m2"
                type="number"
                value={item.weight_g_m2 || ''}
                onChange={(e) => onChange({ weight_g_m2: e.target.value ? Number(e.target.value) : null })}
                disabled={!canEdit}
                placeholder="g/m²"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="dyeing_batch_size">{t('catalog.dyeingBatchSize')}</Label>
              <Input
                id="dyeing_batch_size"
                type="number"
                value={item.dyeing_batch_size || ''}
                onChange={(e) => onChange({ dyeing_batch_size: e.target.value ? Number(e.target.value) : null })}
                disabled={!canEdit}
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>{t('catalog.producedUnit')}</Label>
              <Select
                value={item.produced_unit}
                onValueChange={(value) => onChange({ produced_unit: value })}
                disabled={!canEdit}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {UNIT_OPTIONS.map(opt => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>{t('catalog.soldUnit')}</Label>
              <Select
                value={item.sold_unit}
                onValueChange={(value) => onChange({ sold_unit: value })}
                disabled={!canEdit}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {UNIT_OPTIONS.map(opt => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="flex items-center justify-between">
            <Label htmlFor="eu_origin">{t('catalog.euOrigin')}</Label>
            <Switch
              id="eu_origin"
              checked={item.eu_origin}
              onCheckedChange={(checked) => onChange({ eu_origin: checked })}
              disabled={!canEdit}
            />
          </div>
        </CardContent>
      </Card>

      {/* Additional Information */}
      <Card className="lg:col-span-2">
        <CardHeader>
          <CardTitle className="text-lg">{t('catalog.additionalInfo')}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="care_instructions">{t('catalog.careInstructions')}</Label>
              <Textarea
                id="care_instructions"
                value={item.care_instructions || ''}
                onChange={(e) => onChange({ care_instructions: e.target.value || null })}
                disabled={!canEdit}
                rows={3}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="sustainable_notes">{t('catalog.sustainableNotes')}</Label>
              <Textarea
                id="sustainable_notes"
                value={item.sustainable_notes || ''}
                onChange={(e) => onChange({ sustainable_notes: e.target.value || null })}
                disabled={!canEdit}
                rows={3}
              />
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="product_notes">{t('catalog.productNotes')}</Label>
            <Textarea
              id="product_notes"
              value={item.product_notes || ''}
              onChange={(e) => onChange({ product_notes: e.target.value || null })}
              disabled={!canEdit}
              rows={3}
            />
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default CatalogOverviewTab;
