import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'tr';
  setLanguage: (lang: 'en' | 'tr') => void;
  t: (key: string) => string | string[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    lotIntake: 'LOT Intake',
    inventory: 'Inventory',
    orders: 'Orders',
    qrScan: 'QR Scan',
    orderQueue: 'Order Queue',
    reports: 'Reports',
    suppliers: 'Suppliers',
    admin: 'Admin',
    signOut: 'Sign Out',
    
    // Common
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    create: 'Create',
    update: 'Update',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    
    // Dashboard
    welcomeMessage: 'Welcome to Warehouse LOT Tracking',
    totalLots: 'Total Lots',
    totalRolls: 'Total Rolls',
    totalMeters: 'Total Meters',
    totalOrders: 'Total Orders',
    pendingOrders: 'Pending Orders',
    recentActivity: 'Recent Activity',
    welcomeBack: 'Welcome back',
    lotAgingAlert: 'LOT Aging Alert',
    monitorOldInventory: 'Monitor old inventory',
    oldestLot: 'Oldest LOT in inventory',
    quickActions: 'Quick Actions',
    commonTasks: 'Common tasks for your role',
    days: 'days',
    noLotsInInventory: 'No LOTs in inventory',
    considerReviewing: 'Consider reviewing old stock',
    overview: 'Overview',
    lotIntakeShort: 'LOT Intake',
    scanQr: 'Scan QR',
    createOrderShort: 'Create Order',
    viewReports: 'View Reports',
    inStockLotsAvailable: 'In-stock lots available',
    totalRollsInventory: 'Total rolls in inventory',
    totalMetersInventory: 'Total meters in inventory',
    awaitingFulfillment: 'Awaiting fulfillment',
    manageSuppliers: 'Manage Suppliers',
    addEditManageSupplier: 'Add, edit, and manage supplier information',
    deleteLots: 'Delete Lots',
    removeLotsFromSystem: 'Remove lots from inventory system',
    reprintQrCodes: 'Reprint QR Codes',
    regenerateAndPrintQr: 'Regenerate and print QR codes for lots',
    goToSuppliers: 'Go to Suppliers',
    goToInventory: 'Go to Inventory',
    goToLotIntake: 'Go to Lot Intake',
    
    // Inventory
    qualityFilter: 'Filter by Quality',
    colorFilter: 'Filter by Color',
    searchPlaceholder: 'Search lots, quality, color...',
    importExcel: 'Import Excel',
    stockOverview: 'Stock Overview',
    expandableView: 'Expandable view of inventory grouped by quality and color',
    filtersSearch: 'Filters & Search',
    filterInventory: 'Filter inventory by quality, color, or search terms',
    allQualities: 'All Qualities',
    allColors: 'All Colors',
    allStatuses: 'All Statuses',
    multiple: 'Multiple',
    allStatus: 'All Status',
    exportExcel: 'Export Excel',
    noInventoryItems: 'No inventory items found matching your filters.',
    rolls: 'rolls',
    meters: 'meters',
    lots: 'LOTs',
    age: 'Age',
    status: 'Status',
    entryDate: 'Entry Date',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    partiallyFulfilled: 'Partially Fulfilled',
    downloadTemplate: 'Download Template',
    uploadFile: 'Upload File',
    importStarted: 'Import Started',
    processingRows: 'Processing rows from CSV file...',
    importError: 'Import Error',
    failedToParse: 'Failed to parse CSV file.',
    showing: 'Showing',
    addToOrder: 'Add to Order',
    clear: 'Clear',
    quality: 'Quality',
    color: 'Color',
    lotNumber: 'Lot Number',
    supplier: 'Supplier',
    
    // Orders
    orderNumber: 'Order Number',
    customerName: 'Customer Name',
    orderCreation: 'Create Order',
    selectLots: 'Select Lots',
    addLot: 'Add LOT',
    createNewOrder: 'Create New Order',
    orderCreated: 'Order Created',
    orderCreatedSuccessfully: 'Order created successfully',
    failedToCreateOrder: 'Failed to create order',
    orderManagement: 'Order Management',
    viewAllOrders: 'View and manage all orders in the system',
    createdBy: 'Created By',
    createdAt: 'Created At',
    fulfilledBy: 'Fulfilled By',
    fulfilledAt: 'Fulfilled At',
    pending: 'Pending',
    fulfilled: 'Fulfilled',
    noOrdersFound: 'No orders found.',
    newOrder: 'New Order',
    standardOrder: 'Standard Order',
    multiQualityOrder: 'Multi-Quality Order',
    bulkUploadOrders: 'Bulk Upload Orders',
    sampleOrder: 'Sample Order',
    customer: 'Customer',
    selectedLots: 'Selected LOTs',
    addLotButton: 'Add LOT',
    lotCount: 'Lot Count',
    rollCount: 'Roll Count',
    differentColors: 'different colors',
    type: 'Type',
    standard: 'Standard',
    sample: 'Sample',
    remove: 'Remove',
    createOrderButton: 'Create Order',
    orderManagementDesc: 'View and manage customer orders',
    lotsCount: 'LOTs Count',
    created: 'Created',
    orderDetails: 'Order Details',
    deletedSuccessfully: 'deleted successfully',
    confirmDelete: 'Confirm Delete',
    confirmDeleteLot: 'Are you sure you want to delete lot',
    actionCannotBeUndone: 'This action cannot be undone.',
    deleteMode: 'Delete Mode',
    deleteSelected: 'Delete Selected',
    confirmDeleteQualityColor: 'Are you sure you want to delete all lots for quality "{quality}" and color "{color}"?',
    
    // Lot Intake
    lotIntakeNumber: 'Lot Number',
    intakeMeters: 'Meters',
    intakeRollCount: 'Roll Count',
    intakeQuality: 'Quality',
    intakeColor: 'Color',
    intakeSupplier: 'Supplier',
    createLot: 'Create LOT',
    lotIntakeForm: 'LOT Intake Form',
    enterNewLot: 'Enter new LOT details into the system',
    lotCreated: 'LOT Created',
    lotCreatedSuccessfully: 'LOT created successfully',
    failedToCreateLot: 'Failed to create LOT',
    required: 'Required',
    newLotEntry: 'New roll entry to stock',
    newLotDescription: 'Enter new textile roll LOT details',
    productionDate: 'Production Date',
    invoiceDate: 'Invoice Date',
    invoiceNumber: 'Invoice Number',
    warehouseLocation: 'Warehouse Location',
    notes: 'Notes',
    creatingLot: 'Creating LOT...',
    qrCodeGenerated: 'QR Code Generated',
    printQrCode: 'Print QR Code',
    optionalFields: 'Optional Information',
    generateQr: 'Generate QR',
    quickQrEntry: 'Quick QR Entry',
    generateQrDescription: 'Generate a QR code for a new lot',
    lotQueue: 'Lot Queue',
    pendingLots: 'Pending Lots',
    lotQueueDescription: 'Lots pending completion by accounting/admin users',
    completeLotInfo: 'Complete Lot Information',
    moveToInventory: 'Move to Inventory',
    allLotsCompleted: 'All lots have been completed and moved to inventory.',
    
    // QR Scanner
    qrCodeScanner: 'QR Code Scanner',
    lotLookup: 'LOT Lookup',
    searchForLot: 'Search for LOT details by number or scan QR code',
    enterLotNumber: 'Enter LOT number (e.g., LOT001)',
    searching: 'Searching...',
    lotDetails: 'LOT Details',
    lotNotFound: 'LOT number not found',
    failedToFetch: 'Failed to fetch LOT details',
    oldLotWarning: 'This LOT is over {days} days old. Consider reviewing for aging inventory.',
    howToUse: 'How to Use QR Scanner',
    qrInstructions: [
      'Use any QR code scanner app on your mobile device',
      'Scan the QR code printed on the textile roll',
      "You'll be redirected to this page with LOT details",
      'Alternatively, you can manually enter the LOT number above'
    ],
    scanQrCode: 'Scan QR Code',
    uploadQrImage: 'Upload QR Image',
    selectLotFrom: 'Select LOT from inventory',
    qrCodeScanned: 'QR Code Scanned',
    pleaseLogin: 'Please log in to view LOT details',
    signInToView: 'Sign In to View Details',
    qrScanner: 'QR Scanner',
    scanCode: 'Scan Code',
    uploadImage: 'Upload Image',
    selectLot: 'Select LOT',
    selectLotPlaceholder: 'Choose a LOT to view details',
    noFileSelected: 'No file selected',
    chooseFile: 'Choose File',
    
    // Reports
    reportsAnalytics: 'Reports & Analytics',
    generateReports: 'Generate comprehensive reports and analytics',
    
    // Admin
    adminPanel: 'Admin Panel',
    systemAdministration: 'System administration and management tools',
    addUser: 'Add User',
    userManagement: 'User Management',
    permissions: 'Permissions',
    totalUsers: 'Total Users',
    admins: 'Admins',
    seniorManagers: 'Senior Managers',
    activeSystemUsers: 'Active system users',
    administratorAccounts: 'Administrator accounts',
    seniorManagersDesc: 'Senior managers',
    accountingUsers: 'Accounting users',
    warehousePersonnel: 'Warehouse personnel',
    noNameSet: 'No name set',
    editUser: 'Edit User',
    addNewUser: 'Add New User',
    deleteUser: 'Delete User',
    warehouseStaffRole: 'Warehouse Staff',
    accountingRole: 'Accounting',
    seniorManagerRole: 'Senior Manager',
    adminRole: 'Admin',
    deleteConfirmation: 'Are you sure you want to delete user "{name}"? This action cannot be undone and will permanently remove all user data.',
    userCreatedSuccessfully: 'User Created Successfully',
    userCreatedTempPassword: 'User created with temporary password: {password}. Please share this with the user securely.',
    userCreationFailed: 'User Creation Failed',
    failedToCreateUser: 'Failed to create user. Please try again.',
    profileUpdatedSuccessfully: 'Profile updated successfully.',
    failedToUpdateProfile: 'Failed to update profile.',
    userDeletedSuccessfully: 'User {name} deleted successfully.',
    failedToDeleteUser: 'Failed to delete user. You may need admin service role key.',
    changePassword: 'Change Password',
    changePasswordFor: 'Change Password for {name}',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters long',
    passwordTooWeak: 'Password is too weak. Use at least 8 characters with numbers and special characters.',
    passwordCompromised: 'This password has been compromised in data breaches. Please choose a different one.',
    passwordChangedSuccessfully: 'Password changed successfully',
    failedToChangePassword: 'Failed to change password',
    errorFetchingProfiles: 'Failed to fetch user profiles.',
    notAuthorizedAccess: 'You are not authorized to access this page.',
    
    // Suppliers
    supplierManagement: 'Supplier Management',
    
    // Dashboard Quick Actions
    createNewLotEntries: 'Create new LOT entries',
    scanQrCodes: 'Scan QR codes', 
    fulfillOrders: 'Fulfill orders',
    createNewOrders: 'Create new orders',
    checkStockLevels: 'Check stock levels',
    generateReportsAction: 'Generate reports',
    
    // Additional Orders translations
    newOrderCreate: 'New Order',
    createOrderForm: 'Create New Order',
    enterOrderDetails: 'Enter order details and select LOTs for fulfillment',
    orderNumberField: 'Order Number',
    customerNameField: 'Customer Name',
    orderManagementSection: 'Order Management',
    viewManageOrders: 'View and manage customer orders',
    lotNumberShort: 'LOT Number',
    rollsShort: 'Rolls',
    typeShort: 'Type',
    orderDetailsModal: 'Order Details',
    fulfilledStatus: 'Fulfilled',
    validationError: 'Validation Error',
    fillAllFields: 'Please fill in all fields and select at least one LOT',
    orderCreatedDesc: 'has been created successfully',
    errorCreatingOrder: 'Error Creating Order',
    orderFulfilled: 'Order Fulfilled',
    orderMarkedFulfilled: 'Order has been marked as fulfilled',
    errorFulfillingOrder: 'Error Fulfilling Order',
    orderDate: 'Order Date',
    lineType: 'Line Type',
    metersPerRoll: 'Meters per Roll',
    
    // Permissions
    permissionsTitle: 'Role Hierarchy & Permissions',
    
    // Role Names
    roleWarehouseStaff: 'WAREHOUSE STAFF',
    roleAccounting: 'ACCOUNTING',
    roleSeniorManager: 'SENIOR MANAGER',
    roleAdmin: 'ADMIN',
    
    // Role Descriptions
    roleDescWarehouseStaff: 'Basic operations',
    roleDescAccounting: 'Financial operations',
    roleDescSeniorManager: 'All operations except user management',
    roleDescAdmin: 'Full system access',
    
    // Permission Categories
    categoryUserManagement: 'User Management',
    categoryInventory: 'Inventory',
    categoryOrders: 'Orders',
    categorySuppliers: 'Suppliers',
    categoryReports: 'Reports',
    categoryQrDocuments: 'QR & Documents',
    
    // User Management Actions
    actionViewUsers: 'View Users',
    actionCreateUsers: 'Create Users',
    actionEditUsers: 'Edit Users',
    actionDeleteUsers: 'Delete Users',
    actionManageRoles: 'Manage Roles',
    actionChangePermissions: 'Change Permissions',
    
    // Inventory Actions
    actionCreateLotEntries: 'Create Lot Entries',
    actionViewInventory: 'View Inventory',
    actionEditLotInfo: 'Edit Lot Information',
    actionDeleteLotEntries: 'Delete Lot Entries',
    actionGenerateQrCodes: 'Generate QR Codes',
    
    // Order Actions
    actionViewOrders: 'View Orders',
    actionCreateOrders: 'Create Orders',
    actionEditOrders: 'Edit Orders',
    actionDeleteOrders: 'Delete Orders',
    actionFulfillOrders: 'Fulfill Orders',
    actionPrintOrderDocs: 'Print Order Documents',
    
    // Supplier Actions
    actionViewSuppliers: 'View Suppliers',
    actionCreateSuppliers: 'Create Suppliers',
    actionEditSuppliers: 'Edit Suppliers',
    actionDeleteSuppliers: 'Delete Suppliers',
    
    // Report Actions
    actionViewReports: 'View Reports',
    actionExportReports: 'Export Reports',
    actionAccessDashboard: 'Access Dashboard Analytics',
    
    // QR & Documents Actions
    actionScanQrCodes: 'Scan QR Codes',
    actionPrintLotLabels: 'Print Lot Labels',
    actionBulkQrGeneration: 'Bulk QR Generation',
    
    // Table Headers
    tableHeaderAction: 'Action',
    tableHeaderWarehouseStaff: 'Warehouse Staff',
    tableHeaderAccounting: 'Accounting',
    tableHeaderSeniorManager: 'Senior Manager',
    tableHeaderAdmin: 'Admin',

    // Add missing translations
    allOrders: 'All Orders',
    poCart: 'PO Cart',
    cart: 'Cart',
    addToCart: 'Add to Cart',
    addedToCart: 'Added to Cart',
    addAllToCart: 'Add All to Cart',
    createPO: 'Create PO',
    continueShopping: 'Continue Shopping',
    addMoreColors: 'Add More Colors',
    addDifferentQuality: 'Add Different Quality',
    createOrder: 'Create Order',
    clearAll: 'Clear All', 
    backToInventory: 'Back to Inventory',
    backToColorSelection: 'Go Back to Color Selection',
    qualityColors: 'Quality-Colors',
    daysOld: 'days old',
    availableColors: 'Available Colors',
    selectLotsAction: 'Select Lots',
    selectActionPage: 'Select',
    actionAdd: 'Action',
    viewQuality: 'View Quality',
    selectForSample: 'Select for Sample',
    unknownValue: 'Unknown',
    selectQualityColor: "Select Quality & Color",
    selectQualityColorDescription: "Choose the quality and color to filter available lots.",
    selectQuality: "Select Quality",
    selectColor: "Select Color",
    selectLotsButton: "Select Lots",
    backToOrders: "Back to Orders",
    rollsToOrder: "Rolls to Order",
    selectedLotsSummary: "Selected Lots Summary",
    clearSelection: "Clear Selection",
    proceedToOrder: "Proceed to Order",
    lotsPlural: "lots",
    selectedCount: "selected",
    filters: "Filters",
    searchLots: "Search lots...",
    dateRange: "Date Range",
    allDates: "All Dates",
    today: "Today",
    lastWeek: "Last Week",
    lastMonth: "Last Month",
    allSuppliers: "All Suppliers",
    clearFilters: "Clear Filters",
    noLotsAvailable: "No lots available for the selected criteria",
    enterCustomerDetails: "Enter customer details to complete the order",
    selectedLotsLabel: "Selected Lots",
    rollsLabel: "rolls",
    seeRolls: "See Rolls",
    rollDetails: "Roll Details", 
    rollPosition: "Position",
    rollMeters: "Roll Meters",
    stockEntryDate: "Stock Entry Date",
    totalRollsInLot: "Total Rolls in Lot",
    selectRolls: "Select Rolls",
    selectedMeters: "Selected Meters",
    selectAll: "Select All",
    addSelectedToCart: "Add Selected to Cart",
    
    // Authentication
    signIn: 'Sign In',
    email: 'Email',
    password: 'Password',
    signingIn: 'Signing in...',
    signInFailed: 'Sign in failed',
    welcomeBackAuth: 'Welcome back!',
    signInSuccess: 'You have been signed in successfully.',
    invalidCredentials: 'Invalid email or password. Please check your credentials and try again.',
    authDescription: 'Sign in to access the warehouse management system',
    emailDomainNotAllowed: 'Email domain not allowed. Please contact administrator to allow {domain} domain, or try a different email address.',
    signUp: 'Sign Up',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    resetPasswordDescription: 'Enter your email address and we\'ll send you a link to reset your password.',
    sendResetLink: 'Send Reset Link',
    sending: 'Sending...',
    resetEmailSent: 'Password Reset Email Sent',
    resetEmailSentDescription: 'Check your email for password reset instructions.',
    resetEmailFailed: 'Password Reset Failed',
    
    // Lot Entry Mode Translations  
    singleLotEntry: "Single Lot Entry",
    bulkLotImport: "Bulk Lot Import", 
    chooseEntryMethod: "Choose Entry Method",
    singleEntryDescription: "Manually enter individual lot information",
    bulkImportDescription: "Import multiple lots via CSV/Excel file",
    selectFile: "Select File",
    processingFile: "Processing file...",
    validatingData: "Validating data...",
    templateDownloaded: "Template downloaded successfully",
    importing: "Importing...",
    importFile: "Import File",
    progress: "Progress",
    importResults: "Import Results",
    errors: "Errors",
    failed: "Failed",
    
    // Bulk Import Translations
    bulkImportInstructions: "Import multiple lots from a CSV file. Follow the exact column order for successful import.",
    lotCreatedSuccessMessage: "created successfully",
    errorsFound: "errors found", 
    downloadErrorReport: "Download Error Report",
    parsingErrors: "Parsing Errors",
    databaseErrors: "Database Errors", 
    rowError: "Row",
    moreParsingErrors: "more parsing errors",
    moreDatabaseErrors: "more database errors",
    selectFileToImport: "Please select a file to import",
    validationFailed: "Validation failed",
    errorsFoundInFile: "errors found in the uploaded file. Please fix the errors and upload again.",
    browseFile: "Browse File",
    
    // Sample Order Translations
    sampleRollSelection: 'Sample Roll Selection',
    sampleMeters: 'Sample Meters:',
    sampleModeInstructions: 'Select one roll and specify the sample meters needed.',
    sampleMetersLabel: 'Sample Meters (max {max}m):',
    enterSampleMeters: 'Enter sample meters',
    addSampleButton: 'Add Sample ({meters}m)',
    
    // Approvals
    approvals: 'Approvals for changes',
    accessDenied: 'Access Denied',
    requiresApprovalPermissions: 'You need approval permissions to access this page',
    approvalQueues: 'Approval Queues',
    inventoryChanges: 'Inventory Changes',
    orderChanges: 'Order Changes',
    pendingInventoryChanges: 'Pending Inventory Changes',
    pendingOrderChanges: 'Pending Order Changes',
    noPendingInventoryChanges: 'No pending inventory changes',
    noPendingOrderChanges: 'No pending order changes',
    pendingCount: 'Pending',
    approve: 'Approve',
    reject: 'Reject',
    rejectItem: 'Reject Item',
    rejectionReason: 'Rejection Reason',
    rejectionReasonPlaceholder: 'Please provide a reason for rejection...',
    location: 'Location',
    submitted: 'Submitted',
    submittedBy: 'Submitted By',
    orderId: 'Order ID',
    approved: 'Approved',
    rejected: 'Rejected',
    approvalPermissionDenied: "You don't have permission to view approval queues.",
    lotApprovedToast: 'has been approved and added to inventory.',
    lotRejectedToast: 'has been rejected.',
    orderApprovedToast: 'Order has been approved.',
    orderRejectedToast: 'Order has been rejected.',
  },
  tr: {
    // Navigation
    dashboard: 'Kontrol Paneli',
    lotIntake: 'LOT Girişi',
    inventory: 'Envanter',
    orders: 'Siparişler',
    qrScan: 'QR Tarama',
    orderQueue: 'Sipariş Kuyruğu',
    reports: 'Raporlar',
    suppliers: 'Tedarikçiler',
    admin: 'Yönetici',
    signOut: 'Çıkış Yap',
    
    // Common
    search: 'Ara',
    filter: 'Filtrele',
    export: 'Dışa Aktar',
    save: 'Kaydet',
    cancel: 'İptal',
    edit: 'Düzenle',
    delete: 'Sil',
    create: 'Oluştur',
    update: 'Güncelle',
    loading: 'Yükleniyor...',
    error: 'Hata',
    success: 'Başarılı',
    previous: 'Önceki',
    next: 'Sonraki',
    page: 'Sayfa',
    of: 'of',
    selected: 'seçili',
    
    // Dashboard
    welcomeMessage: 'Depo LOT Takip Sistemine Hoş Geldiniz',
    totalLots: 'Toplam Lot',
    totalRolls: 'Stoktaki top sayısı',
    totalMeters: 'Stoktaki toplam metraj sayısı',
    totalOrders: 'Toplam Sipariş',
    pendingOrders: 'Bekleyen siparişler',
    recentActivity: 'Son Aktiviteler',
    welcomeBack: 'Tekrar hoş geldiniz',
    lotAgingAlert: 'LOT Yaşlanma Uyarısı',
    monitorOldInventory: 'Eski envanteri izle',
    oldestLot: 'Envanterdeki en eski LOT',
    quickActions: 'Hızlı İşlemler',
    commonTasks: 'Rolünüz için genel görevler',
    days: 'gün',
    noLotsInInventory: 'Envanterde LOT yok',
    considerReviewing: 'Eski stoku gözden geçirmeyi düşünün',
    overview: 'Genel Bakış',
    lotIntakeShort: 'LOT Girişi',
    scanQr: 'QR Tara',
    createOrderShort: 'Sipariş Oluştur',
    viewReports: 'Raporları Gör',
    inStockLotsAvailable: 'stoktaki toplam lot sayısı',
    totalRollsInventory: 'Stoktaki top sayısı',
    totalMetersInventory: 'Stoktaki toplam metraj sayısı',
    awaitingFulfillment: 'Bekleyen siparişler',
    manageSuppliers: 'Tedarikçileri yönet',
    addEditManageSupplier: 'tedarikçi bilgilerini güncelle',
    deleteLots: 'lot sil',
    removeLotsFromSystem: 'sistemden lotları sil',
    reprintQrCodes: 'Toplar için QR kodları yazdır',
    regenerateAndPrintQr: 'QR kodlarını yeniden oluştur ve yazdır',
    goToSuppliers: 'tedarikçilere git',
    goToInventory: 'stoğa git',
    goToLotIntake: 'QR yönetim sayfasına git',
    
    // Inventory
    qualityFilter: 'Kaliteye Göre Filtrele',
    colorFilter: 'Renge Göre Filtrele',
    searchPlaceholder: 'Lot, kalite, renk ara...',
    importExcel: 'Excel İçe Aktar',
    stockOverview: 'Stok Genel Görünümü',
    expandableView: 'Kalite ve renge göre gruplanmış envanterin genişletilebilir görünümü',
    filtersSearch: 'Filtreler ve Arama',
    filterInventory: 'Envanteri kalite, renk veya arama terimlerine göre filtrele',
    allQualities: 'Tüm Kaliteler',
    allColors: 'Tüm Renkler',
    allStatuses: 'Tüm Durumlar',
    multiple: 'Çoklu',
    allStatus: 'Tüm Durumlar',
    exportExcel: 'Excel Dışa Aktar',
    noInventoryItems: 'Filtrelerinizle eşleşen envanter öğesi bulunamadı.',
    rolls: 'Top Sayısı',
    meters: 'Toplam Depo Metrajı',
    lots: 'Farklı Lot Sayısı',
    age: 'Yaş',
    status: 'Durum',
    entryDate: 'Giriş Tarihi',
    inStock: 'Stokta',
    outOfStock: 'Stok Yok',
    partiallyFulfilled: 'Kısmen Karşılandı',
    downloadTemplate: 'Şablon İndir',
    uploadFile: 'Dosya Yükle',
    importStarted: 'İçe Aktarma Başladı',
    processingRows: 'CSV dosyasından satırlar işleniyor...',
    importError: 'İçe Aktarma Hatası',
    failedToParse: 'CSV dosyası ayrıştırılamadı.',
    showing: 'Gösteriliyor',
    addToOrder: 'Siparişe Ekle',
    orderSummary: 'Sipariş Özeti',
    print: 'Yazdır',
    warehouseOrderSummary: 'DEPO SİPARİŞ ÖZETİ',
    orderPreparationSheet: 'Sipariş Hazırlama Formu',
    orderInformation: 'Sipariş Bilgileri',
    summary: 'Özet',
    preparedBy: 'Hazırlayan',

    // Add missing translations
    allOrders: 'Tüm Siparişler',
    poCart: 'PO Sepeti',
    cart: 'Sepet',
    addToCart: 'Sepete Ekle',
    addedToCart: 'Sepete Eklendi',
    addAllToCart: 'Tümünü Sepete Ekle',
    createPO: 'Sipariş Oluştur',
    continueShopping: 'Alışverişe Devam Et',
    addMoreColors: 'Daha Fazla Renk Ekle',
    addDifferentQuality: 'Farklı Kalite Ekle',
    createOrder: 'Sipariş Oluştur',
    clearAll: 'Tümünü Temizle',
    backToInventory: 'Envantere Dön',
    backToColorSelection: 'Renklere geri dön',
    qualityColors: 'Kalite-Renk',
    daysOld: 'gün eski',
    availableColors: 'Mevcut Renkler',
    selectLotsAction: 'Lot Seç',
    selectActionPage: 'Seç',
    actionAdd: 'İşlem',
    viewQuality: 'Kalite Gör',
    selectForSample: 'Numune için Seç',
    unknownValue: 'Bilinmeyen',
    selectQualityColor: "Kalite ve Renk Seç",
    selectQualityColorDescription: "Mevcut lotları filtrelemek için kalite ve rengi seçin.",
    selectQuality: "Kalite Seç",
    selectColor: "Renk Seç",
    selectLotsButton: "Lot Seç",
    backToOrders: "Siparişlere Dön",
    availableLots: "Mevcut Lotlar",
    selectAction: "Seç",
    rollsToOrder: "Sipariş Edilecek Toplar",
    selectedLotsSummary: "Seçili Lot Özeti",
    clearSelection: "Seçimi Temizle",
    proceedToOrder: "Siparişe Geç",
    lotsPlural: "lotlar",
    selectedCount: "seçildi",
    filters: "Filtreler",
    searchLots: "Lot ara...",
    dateRange: "Tarih Aralığı",
    allDates: "Tüm Tarihler",
    today: "Bugün",
    lastWeek: "Geçen Hafta",
    lastMonth: "Geçen Ay",
    allSuppliers: "Tüm Tedarikçiler",
    clearFilters: "Filtreleri Temizle",
    noLotsAvailable: "Seçilen kriterlere uygun lot bulunmamaktadır",
    enterCustomerDetails: "Siparişi tamamlamak için müşteri bilgilerini girin",
    selectedLotsLabel: "Seçili Lotlar",
    rollsLabel: "toplar",
    seeRolls: "Topları Gör",
    rollDetails: "Top Detayları",
    rollPosition: "Pozisyon", 
    rollMeters: "Topların Metrajları",
    stockEntryDate: "Stok Giriş Tarihi", 
    totalRollsInLot: "Lottaki Toplam Top Sayısı",
    selectRolls: "top seç",
    selectedMeters: "Seçilen Metre Toplamı", 
    selectAll: "Tümü Seç",
    addSelectedToCart: "Seçilenleri Siparişe Ekle",
    
    // Authentication
    signIn: 'Giriş Yap',
    email: 'E-posta',
    password: 'Şifre',
    signingIn: 'Giriş yapılıyor...',
    signInFailed: 'Giriş başarısız',
    welcomeBackAuth: 'Tekrar hoş geldiniz!',
    signInSuccess: 'Başarıyla giriş yapıldı.',
    invalidCredentials: 'Geçersiz e-posta veya şifre. Bilgilerinizi kontrol edip tekrar deneyin.',
    authDescription: 'Depo yönetim sistemine erişmek için giriş yapın',
    emailDomainNotAllowed: 'E-posta domain\'i izin verilmemiş. {domain} domain\'ine izin vermek için yöneticiye başvurun veya farklı bir e-posta adresi deneyin.',
    signUp: 'Kayıt Ol',
    forgotPassword: 'Şifremi Unuttum?',
    resetPassword: 'Şifre Sıfırla',
    resetPasswordDescription: 'E-posta adresinizi girin, size şifre sıfırlama bağlantısı gönderelim.',
    sendResetLink: 'Sıfırlama Bağlantısı Gönder',
    sending: 'Gönderiliyor...',
    resetEmailSent: 'Şifre Sıfırlama E-postası Gönderildi',
    resetEmailSentDescription: 'Şifre sıfırlama talimatları için e-postanızı kontrol edin.',
    resetEmailFailed: 'Şifre Sıfırlama Başarısız',
    
    // Lot Entry Mode Translations  
    singleLotEntry: "Tekli Lot Girişi",
    bulkLotImport: "Toplu Lot İçe Aktarma", 
    chooseEntryMethod: "Giriş Metodunu Seçin",
    singleEntryDescription: "Tek bir lot bilgisini manuel olarak girin",
    bulkImportDescription: "CSV/Excel dosyası ile toplu lot içe aktarın",
    selectFile: "Dosya Seç",
    processingFile: "Dosya işleniyor...",
    validatingData: "Veriler doğrulanıyor...",
    templateDownloaded: "Şablon başarıyla indirildi",
    importing: "İçe aktarılıyor...",
    importFile: "Dosyayı İçe Aktar",
    progress: "İlerleme",
    importResults: "İçe Aktarma Sonuçları",
    errors: "Hatalar",
    failed: "Başarısız",
    
    // Bulk Import Translations
    bulkImportInstructions: "CSV dosyasından birden fazla lot içe aktarın. Başarılı içe aktarma için tam sütun sırasını takip edin.",
    lotCreatedSuccessMessage: "başarıyla oluşturuldu",
    errorsFound: "hata bulundu",
    downloadErrorReport: "Hata Raporunu İndir", 
    parsingErrors: "Ayrıştırma Hataları",
    databaseErrors: "Veritabanı Hataları",
    rowError: "Satır",
    moreParsingErrors: "daha fazla ayrıştırma hatası",
    moreDatabaseErrors: "daha fazla veritabanı hatası", 
    selectFileToImport: "Lütfen içe aktaracak bir dosya seçin",
    validationFailed: "Doğrulama başarısız",
    errorsFoundInFile: "yüklenen dosyada hata bulundu. Lütfen hataları düzeltin ve tekrar yükleyin.",
    browseFile: "Dosya Yükle",
    prepared: 'Hazırlandı',
    sample: 'Numune',
    standard: 'Standart',
    signatures: 'İmzalar',
    checkedBy: 'Kontrol Eden',
    date: 'Tarih',
    remove: 'Kaldır',
    clear: 'Temizle',
    selectedLotsDisplay: 'lot seçildi',
    
    // Orders
    orderNumber: 'Sipariş Numarası',
    customerName: 'Müşteri Adı',
    orderCreation: 'Sipariş Oluşturma',
    selectLots: 'Lot Seç',
    addLot: 'LOT Ekle',
    createNewOrder: 'Yeni Sipariş Oluştur',
    orderCreated: 'Sipariş Oluşturuldu',
    orderCreatedSuccessfully: 'Sipariş başarıyla oluşturuldu',
    failedToCreateOrder: 'Sipariş oluşturulamadı',
    orderManagement: 'Sipariş Yönetimi',
    viewAllOrders: 'Sistemdeki tüm siparişleri görüntüle ve yönet',
    createdBy: 'Oluşturan',
    createdAt: 'Oluşturulma Tarihi',
    fulfilledBy: 'Karşılayan',
    fulfilledAt: 'Karşılanma Tarihi',
    pending: 'Beklemede',
    fulfilled: 'Karşılandı',
    noOrdersFound: 'Sipariş bulunamadı.',
    newOrder: 'Yeni Sipariş',
    standardOrder: 'Standart Sipariş',
    multiQualityOrder: 'Çoklu Kalite Siparişi',
    bulkUploadOrders: 'Toplu Sipariş Yükleme',
    sampleOrder: 'Numune Siparişi',
    quality: 'Kalite',
    color: 'Renk',
    selectedLotsField: 'Seçilen LOTlar',
    addLotButton: 'LOT Ekle',
    lotCount: 'Lot Sayısı',
    rollCount: 'Top Sayısı',
    differentColors: 'farklı renk',
    typeField: 'Tür',
    standardField: 'Standart',
    sampleField: 'Numune',
    removeOrderField: 'Kaldır',
    createOrderButton: 'Sipariş Oluştur',
    orderManagementDesc: 'Müşteri siparişlerini görüntüle ve yönet',
    lotsCount: 'LOT Sayısı',
    created: 'Oluşturuldu',
    actions: 'İşlemler',
    orderDetailsField: 'Sipariş Detayları',
    deletedSuccessfully: 'başarıyla silindi',
    confirmDelete: 'Silme İşlemini Onayla',
    confirmDeleteLot: 'Şu lotu silmek istediğinizden emin misiniz:',
    actionCannotBeUndone: 'Bu işlem geri alınamaz.',
    deleteMode: 'Silme Modu',
    deleteSelected: 'Seçilenleri Sil',
    confirmDeleteQualityColor: '"{quality}" kalitesi ve "{color}" rengindeki tüm lotları silmek istediğinizden emin misiniz?',
    
    // Lot Intake
    lotIntakeNumber: 'Lot Numarası',
    intakeMeters: 'Metre',
    intakeRollCount: 'Rulo Sayısı',
    intakeQuality: 'Kalite',
    intakeColor: 'Renk',
    intakeSupplier: 'Tedarikçi',
    createLot: 'LOT Oluştur',
    lotIntakeForm: 'LOT Giriş Formu',
    enterNewLot: 'Sisteme yeni LOT detayları girin',
    lotCreated: 'LOT Oluşturuldu',
    lotCreatedSuccessfully: 'LOT başarıyla oluşturuldu',
    failedToCreateLot: 'LOT oluşturulamadı',
    required: 'Gerekli',
    newLotEntry: 'Yeni Top Stoğa Girişi',
    newLotDescription: 'Yeni tekstil rulosu LOT detaylarını girin',
    productionDate: 'Üretim Tarihi',
    invoiceDate: 'Fatura Tarihi',
    invoiceNumber: 'Fatura Numarası',
    warehouseLocation: 'Depo Konumu',
    notes: 'Notlar',
    creatingLot: 'LOT Oluşturuluyor...',
    qrCodeGenerated: 'QR Kod Oluşturuldu',
    printQrCode: 'QR Kodu Yazdır',
    optional: 'Opsiyonel',
    optionalFields: 'Zorunlu olmayan bilgiler',
    generateQr: 'QR Oluştur',
    quickQrEntry: 'Hızlı QR Girişi',
    generateQrDescription: 'Yeni lot için QR kodu oluştur',
    lotQueue: 'Lot Kuyruğu',
    pendingLots: 'Bekleyen Lotlar',
    lotQueueDescription: 'Depo tarafından oluşturulan lotların bilgisinin tamamlanması ve sisteme girilmesi için aşağıdaki listeyi kontrol ediniz',
    completeLotInfo: 'Lot Bilgilerini Tamamla',
    moveToInventory: 'Envantere Taşı',
    allLotsCompleted: 'Tüm lotların bilgisi tamamlanmış ve stoğa girmiştir, bekleyen lot bulunmamaktadır.',
    
    // QR Scanner
    qrCodeScanner: 'QR Kod Tarayıcısı',
    lotLookup: 'LOT Arama',
    searchForLot: 'Numara ile LOT detaylarını ara veya QR kod tara',
    enterLotNumber: 'LOT numarası girin (örn: LOT001)',
    searching: 'Aranıyor...',
    lotDetails: 'LOT Detayları',
    lotNotFound: 'LOT numarası bulunamadı',
    failedToFetch: 'LOT detayları getirilemedi',
    oldLotWarning: 'Bu LOT {days} günlükten eski. Yaşlanan envanter için gözden geçirmeyi düşünün.',
    howToUse: 'QR Tarayıcısı Nasıl Kullanılır',
    qrInstructions: [
      'Mobil cihazınızda herhangi bir QR kod tarayıcı uygulaması kullanın',
      'Tekstil rulosunda basılı QR kodu tarayın',
      'LOT detayları ile bu sayfaya yönlendirileceksiniz',
      'Alternatif olarak, yukarıda LOT numarasını manuel olarak girebilirsiniz'
    ],
    scanQrCode: 'QR Kod Tara',
    uploadQrImage: 'QR Resmi Yükle',
    selectLotFrom: 'Envanterden LOT seç',
    qrCodeScanned: 'QR Kod Tarandı',
    pleaseLogin: 'LOT detaylarını görüntülemek için lütfen giriş yapın',
    signInToView: 'Detayları Görüntülemek İçin Giriş Yap',
    qrScanner: 'QR Tarayıcı',
    scanCode: 'Kod Tara',
    uploadImage: 'Resim Yükle',
    selectLot: 'LOT Seç',
    selectLotPlaceholder: 'Detayları görmek için bir LOT seçin',
    noFileSelected: 'Dosya seçilmedi',
    chooseFile: 'Dosya Seç',
    
    // Reports
    reportsAnalytics: 'Raporlar ve Analitik',
    generateReports: 'Kapsamlı raporlar ve analitik oluştur',
    
    // Admin
    adminPanel: 'Yönetici Paneli',
    systemAdministration: 'Sistem yönetimi ve yönetim araçları',
    addUser: 'Kullanıcı Ekle',
    userManagement: 'Kullanıcı Yönetimi',
    permissions: 'İzinler',
    totalUsers: 'Toplam Kullanıcı',
    admins: 'Yöneticiler',
    seniorManagers: 'Üst Düzey Yöneticiler',
    activeSystemUsers: 'Aktif sistem kullanıcıları',
    administratorAccounts: 'Yönetici hesapları',
    seniorManagersDesc: 'Üst düzey yöneticiler',
    accountingUsers: 'Muhasebe kullanıcıları',
    warehousePersonnel: 'Depo personeli',
    noNameSet: 'İsim ayarlanmamış',
    editUser: 'Kullanıcıyı Düzenle',
    addNewUser: 'Yeni Kullanıcı Ekle',
    deleteUser: 'Kullanıcıyı Sil',
    warehouseStaffRole: 'Depo Personeli',
    accountingRole: 'Muhasebe',
    seniorManagerRole: 'Üst Düzey Yönetici',
    adminRole: 'Yönetici',
    deleteConfirmation: '"{name}" kullanıcısını silmek istediğinizden emin misiniz? Bu işlem geri alınamaz ve tüm kullanıcı verilerini kalıcı olarak kaldırır.',
    userCreatedSuccessfully: 'Kullanıcı Başarıyla Oluşturuldu',
    userCreatedTempPassword: 'Geçici şifre ile kullanıcı oluşturuldu: {password}. Lütfen bunu güvenli bir şekilde kullanıcıyla paylaşın.',
    userCreationFailed: 'Kullanıcı Oluşturma Başarısız',
    failedToCreateUser: 'Kullanıcı oluşturulamadı. Lütfen tekrar deneyin.',
    profileUpdatedSuccessfully: 'Profil başarıyla güncellendi.',
    failedToUpdateProfile: 'Profil güncellenemedi.',
    userDeletedSuccessfully: 'Kullanıcı {name} başarıyla silindi.',
    failedToDeleteUser: 'Kullanıcı silinemedi. Yönetici servis rol anahtarına ihtiyacınız olabilir.',
    changePassword: 'Şifre Değiştir',
    changePasswordFor: '{name} için Şifre Değiştir',
    newPassword: 'Yeni Şifre',
    confirmPassword: 'Şifreyi Onayla',
    passwordsDoNotMatch: 'Şifreler eşleşmiyor',
    passwordTooShort: 'Şifre en az 6 karakter olmalıdır',
    passwordTooWeak: 'Şifre çok zayıf. En az 8 karakter kullanın ve sayılar ile özel karakterler ekleyin.',
    passwordCompromised: 'Bu şifre veri ihlallerinde ele geçirilmiş. Lütfen farklı bir şifre seçin.',
    passwordChangedSuccessfully: 'Şifre başarıyla değiştirildi',
    failedToChangePassword: 'Şifre değiştirilemedi',
    errorFetchingProfiles: 'Kullanıcı profillerini getirme başarısız.',
    notAuthorizedAccess: 'Bu sayfaya erişim yetkiniz yoktur.',
    
    // Suppliers
    supplierManagement: 'Tedarikçi Yönetimi',
    
    // Dashboard Quick Actions
    createNewLotEntries: 'Yeni LOT girişleri oluştur',
    scanQrCodes: 'QR kodları tara',
    fulfillOrders: 'Siparişleri karşıla',
    createNewOrders: 'Yeni siparişler oluştur', 
    checkStockLevels: 'Stok seviyelerini kontrol et',
    generateReportsAction: 'Raporlar oluştur',
    
    // Additional Orders translations
    newOrderCreate: 'Yeni Sipariş',
    createOrderForm: 'Yeni Sipariş Oluştur',
    enterOrderDetails: 'Sipariş detaylarını girin ve karşılanacak LOTları seçin',
    orderNumberField: 'Sipariş Numarası',
    customerNameField: 'Müşteri Adı',
    orderManagementSection: 'Sipariş Yönetimi',
    viewManageOrders: 'Müşteri siparişlerini görüntüle ve yönet',
    lotNumber: 'Lot Numarası',
    rollsShort: 'Rulo',
    typeShort: 'Tür',
    orderDetailsModal: 'Sipariş Detayları',
    fulfilledStatus: 'Karşılandı',
    validationError: 'Doğrulama Hatası',
    fillAllFields: 'Lütfen tüm alanları doldurun ve en az bir LOT seçin',
    orderCreatedDesc: 'başarıyla oluşturuldu',
    errorCreatingOrder: 'Sipariş Oluşturma Hatası',
    orderFulfilled: 'Sipariş Karşılandı',
    orderMarkedFulfilled: 'Sipariş karşılandı olarak işaretlendi',
    errorFulfillingOrder: 'Sipariş Karşılama Hatası',
    orderDate: 'Sipariş Tarihi',
    lineType: 'Sipariş Tipi',
    metersPerRoll: 'Top Başına Metre',
    
    // Permissions
    permissionsTitle: 'Rol Hiyerarşisi ve İzinler',
    
    // Role Names
    roleWarehouseStaff: 'DEPO PERSONELI',
    roleAccounting: 'MUHASEBE',
    roleSeniorManager: 'ÜST YÖNETİCİ',
    roleAdmin: 'YÖNETİCİ',
    
    // Role Descriptions
    roleDescWarehouseStaff: 'Temel işlemler',
    roleDescAccounting: 'Mali işlemler',
    roleDescSeniorManager: 'Kullanıcı yönetimi hariç tüm işlemler',
    roleDescAdmin: 'Tam sistem erişimi',
    
    // Permission Categories
    categoryUserManagement: 'Kullanıcı Yönetimi',
    categoryInventory: 'Envanter',
    categoryOrders: 'Siparişler',
    categorySuppliers: 'Tedarikçiler',
    categoryReports: 'Raporlar',
    categoryQrDocuments: 'QR ve Belgeler',
    
    // User Management Actions
    actionViewUsers: 'Kullanıcıları Görüntüle',
    actionCreateUsers: 'Kullanıcı Oluştur',
    actionEditUsers: 'Kullanıcıları Düzenle',
    actionDeleteUsers: 'Kullanıcıları Sil',
    actionManageRoles: 'Rolleri Yönet',
    actionChangePermissions: 'İzinleri Değiştir',
    
    // Inventory Actions
    actionCreateLotEntries: 'LOT Girişleri Oluştur',
    actionViewInventory: 'Envanteri Görüntüle',
    actionEditLotInfo: 'LOT Bilgilerini Düzenle',
    actionDeleteLotEntries: 'LOT Girişlerini Sil',
    actionGenerateQrCodes: 'QR Kodları Oluştur',
    
    // Order Actions
    actionViewOrders: 'Siparişleri Görüntüle',
    actionCreateOrders: 'Sipariş Oluştur',
    actionEditOrders: 'Siparişleri Düzenle',
    actionDeleteOrders: 'Siparişleri Sil',
    actionFulfillOrders: 'Siparişleri Karşıla',
    actionPrintOrderDocs: 'Sipariş Belgelerini Yazdır',
    
    // Supplier Actions
    actionViewSuppliers: 'Tedarikçileri Görüntüle',
    actionCreateSuppliers: 'Tedarikçi Oluştur',
    actionEditSuppliers: 'Tedarikçileri Düzenle',
    actionDeleteSuppliers: 'Tedarikçileri Sil',
    
    // Report Actions
    actionViewReports: 'Raporları Görüntüle',
    actionExportReports: 'Raporları Dışa Aktar',
    actionAccessDashboard: 'Dashboard Analitiğine Eriş',
    
    // QR & Documents Actions
    actionScanQrCodes: 'QR Kodlarını Tara',
    actionPrintLotLabels: 'LOT Etiketlerini Yazdır',
    actionBulkQrGeneration: 'Toplu QR Oluşturma',
    
    // Table Headers
    tableHeaderAction: 'Eylem',
    tableHeaderWarehouseStaff: 'Depo Personeli',
    tableHeaderAccounting: 'Muhasebe',
    tableHeaderSeniorManager: 'Üst Yönetici',
    tableHeaderAdmin: 'Yönetici',
    
    // Numune Sipariş Çevirileri
    sampleRollSelection: 'Numune Top Seçimi',
    sampleMeters: 'Numune Metrajı:',
    sampleModeInstructions: 'Numune kesilecek topu seçin ve kaç metre gerektiğini belirtin',
    sampleMetersLabel: 'Numune metrajı giriniz (maks {max}m)',
    enterSampleMeters: 'Numune metrajı giriniz',
    addSampleButton: 'Numuneyi Siparişe ekle ({meters}m)',
    
    // Approvals
    approvals: 'Sipariş ve Stok değişiklik talepleri',
    accessDenied: 'Erişim Reddedildi',
    requiresApprovalPermissions: 'Bu sayfaya erişim için onay yetkilerine ihtiyacınız var',
    approvalQueues: 'bekleyen değişiklik talepleri',
    inventoryChanges: 'envanter değişiklik talepleri',
    orderChanges: 'sipariş değişiklik talepleri',
    pendingInventoryChanges: 'bekleyen envanter değişiklik talepleri',
    pendingOrderChanges: 'bekleyen sipariş değişiklikleri',
    noPendingInventoryChanges: 'onay bekleyen envanter değişiklik talebi yok',
    noPendingOrderChanges: 'onay bekleyen sipariş değişiklik talebi yok',
    pendingCount: 'bekleyen değişiklik sayısı',
    approve: 'Onayla',
    reject: 'Reddet',
    rejectItem: 'Öğeyi Reddet',
    rejectionReason: 'Red Nedeni',
    rejectionReasonPlaceholder: 'Lütfen red nedeni belirtin...',
    location: 'Konum',
    submitted: 'Gönderildi',
    submittedBy: 'Gönderen',
    orderId: 'Sipariş ID',
    approved: 'Onaylandı',
    rejected: 'Reddedildi',
    approvalPermissionDenied: "Onay kuyruklarını görüntüleme yetkiniz yok.",
    lotApprovedToast: 'onaylandı ve envantere eklendi.',
    lotRejectedToast: 'reddedildi.',
    orderApprovedToast: 'Sipariş onaylandı.',
    orderRejectedToast: 'Sipariş reddedildi.',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'tr'>('tr');

  const t = (key: string): string | string[] => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};