import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'tr';
  setLanguage: (lang: 'en' | 'tr') => void;
  t: (key: string) => string | string[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    lotIntake: 'LOT Intake',
    inventory: 'Inventory',
    orders: 'Orders',
    qrScan: 'QR Scan',
    orderQueue: 'Order Queue',
    reports: 'Reports',
    suppliers: 'Suppliers',
    admin: 'Admin',
    signOut: 'Sign Out',
    overview: 'Overview',
    inventoryManagement: 'Inventory Management',
    incomingStockLabel: 'Incoming Stock',
    goodsReceipt: 'Goods Receipt',
    ordersAndReservations: 'Orders & Reservations',
    toolsAndUtilities: 'Tools & Utilities',
    reportsAndAdmin: 'Reports & Admin',
    
    // Common
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    create: 'Create',
    update: 'Update',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',

    // Auth
    email: 'Email',
    password: 'Password',
    signIn: 'Sign In',
    register: 'Register',
    signOutConfirmation: 'Are you sure you want to sign out?',
    signOutAction: 'Sign Out',
    
    // Form
    fillAllFields: 'Please fill in all fields.',
    
    // Orders - specific fields
    allOrders: 'All Orders',
    viewManageOrders: 'View and manage existing orders',
    orderNumberField: 'Order Number',
    customer: 'Customer',
    lotsCount: 'Lots Count',
    status: 'Status',
    created: 'Created',
    actions: 'Actions',
    fulfilled: 'Fulfilled',
    view: 'View',
    print: 'Print',
    orderMarkedFulfilled: 'Order marked as fulfilled',
    createOrder: 'Create Order',
    standardOrder: 'Standard Order',
    multiQualityOrder: 'Multi-Quality Order',
    bulkUpload: 'Bulk Upload',
    sampleOrder: 'Sample Order',
    customerNameField: 'Customer Name',
    selectedLots: 'Selected Lots',
    orderCreatedSuccessfully: 'Order created successfully',
    createdOrderNote: 'Created order {orderNumber} for {customerName} with {lotCount} lots, {rollCount} rolls, and {meters} meters',
    fulfilledOrderNote: 'Fulfilled order {orderNumber} for {customerName}',
    deletedOrderNote: 'Deleted order {orderNumber} with {rollCount} rolls',
    deleteOrder: 'Delete Order',
    confirmDelete: 'Confirm Delete',
    actionCannotBeUndone: 'This action cannot be undone.',
    cancelDelete: 'Cancel Delete',
    noSearchResults: 'No search results found.',
    noInventoryData: 'No inventory data available.',
    differentColors: 'Different Colors',
    stockOverview: 'Stock Overview',
    searchPlaceholder: 'Search by quality...',
    viewQuality: 'View Quality',
    deleteMode: 'Delete Mode',
    deleteSelected: 'Delete Selected',
    selectForSample: 'Select for Sample',
    rolls: 'rolls',
    
    // Reservation
    newReservation: 'New Reservation',
    reservationNumber: 'Reservation Number',
    reservedDate: 'Reserved Date',
    totalReservedMeters: 'Total Reserved Meters',
    lines: 'Lines',
    active: 'Active',
    converted: 'Converted',
    reserve: 'Reserve',
    reserveFromIncoming: 'Reserve from Incoming',
    viewReservations: 'View Reservations',
    reservationsForIncoming: 'Reservations for Incoming Stock',
    noReservationsFound: 'No reservations found',
    
    // Orders & Reservations
    allReservations: 'All Reservations',
    activeReservationsTab: 'Active',
    convertedReservationsTab: 'Converted',
    canceledReservationsTab: 'Canceled',
    releasedReservationsTab: 'Released',
    customerId: 'Customer ID',
    holdUntil: 'Hold Until',
    releaseReservation: 'Release Reservation',
    viewDetails: 'View Details',
    cancelReservation: 'Cancel Reservation',
    convertToOrder: 'Convert to Order',
    noReservations: 'No reservations found',
    createReservationFor: 'Create Reservation',
    physicalInventory: 'Physical Inventory',
    incomingStock: 'Incoming Stock',
    customerInformation: 'Customer Information',
    selectItemsToReserve: 'Select Items to Reserve',
    selectedItems: 'Selected Items',
    totalReservedLabel: 'Total Reserved',
    cancelDialog: 'Cancel',
    createReservationButton: 'Create Reservation ({count} items)',
    creating: 'Creating...',
    pleaseAddAtLeastOneLine: 'Please add at least one line item',
    reservationCreated: 'Reservation created successfully',
    optionalCustomerId: 'Customer ID (Optional)',
    optionalHoldUntil: 'Hold Until (Optional)',
    additionalNotes: 'Additional Notes (Optional)',
    totalReserved: 'Total Reserved',
    lineItems: 'Line Items',
    reservationDetails: 'Reservation Details',
    reservedItems: 'Reserved Items',
    scope: 'Scope',
    source: 'Source',
    rollsCount: 'Rolls',
    canceledOn: 'Canceled On',
    canceledBy: 'Canceled By',
    cancelReason: 'Cancel Reason',
    convertedOn: 'Converted On',
    convertedBy: 'Converted By',
    statusHistory: 'Status History',
    closeDialog: 'Close',
    releaseStock: 'Release Stock',
    cancelReservationTitle: 'Cancel Reservation',
    cancelReservationDesc: 'Cancel reservation {reservationNumber} for {customerName}',
    thisWillReleaseStock: 'This will release all reserved stock',
    metersWillBeReleased: '{meters}m will become available again',
    cancellationReason: 'Cancellation Reason',
    selectReason: 'Select a reason',
    customerCanceled: 'Customer Canceled',
    incorrectEntry: 'Incorrect Entry',
    noPayment: 'No Payment Received',
    otherReason: 'Other',
    additionalDetails: 'Additional Details (Required for "Other")',
    explainReason: 'Please explain the reason...',
    keepReservation: 'Keep Reservation',
    confirmCancel: 'Cancel Reservation',
    canceling: 'Canceling...',
    selectCancelReason: 'Please select a cancellation reason',
    provideAdditionalDetails: 'Please provide additional details',
    reservationCanceled: 'Reservation canceled successfully',
    convertReservationTitle: 'Convert to Order',
    convertReservationDesc: 'Convert reservation {reservationNumber} to a sales order',
    noteIncomingLinesWont: 'Note: Incoming lines will not be converted',
    incomingLineCount: '{count} incoming line(s) will remain in the reservation',
    inventoryLineWillConvert: '{count} inventory line(s) will be converted',
    leaveEmptyToUse: 'Leave empty to use: {customerName}',
    createOrderButton: 'Create Order',
    creatingOrder: 'Creating...',
    cannotConvert: 'Cannot convert: reservation contains only incoming stock',
    orderCreated: 'Order created successfully from reservation',
    releaseReservationTitle: 'Release Reservation',
    releaseReservationDesc: 'Release reservation {reservationNumber} for {customerName}',
    releaseInfo: 'This will release reserved stock back to available inventory',
    metersWillBeAvailable: '{meters}m will become available again',
    recordKeepingNote: 'The reservation will remain in the system with status "Released" for record keeping.',
    releaseButton: 'Release Reservation',
    releasing: 'Releasing...',
    reservationReleased: 'Reservation released successfully',
    
    // Audit Logs
    actionCreate: 'Create',
    actionUpdate: 'Update',
    actionDelete: 'Delete',
    actionStatusChange: 'Status Change',
    actionFulfill: 'Fulfill',
    actionApprove: 'Approve',
    actionReject: 'Reject',
    lotsEntity: 'Lots',
    ordersEntity: 'Orders',
    rollsEntity: 'Rolls',
    suppliersEntity: 'Suppliers',
    profilesEntity: 'Profiles',
    lotQueue: 'Lot Queue',
    fieldEditQueue: 'Field Edit Queue',
    rolePermission: 'Role Permission',
    searchByIdentifierOrUser: 'Search by identifier or user...',
    filterByAction: 'Filter by Action',
    filterByEntity: 'Filter by Entity',
    allActions: 'All Actions',
    allEntities: 'All Entities',
    actionDetails: 'Action Details',
    reverseAction: 'Reverse Action',
    reverseActionConfirm: 'Are you sure you want to reverse this action?',
    
    // Lot
    lotNumber: 'Lot Number',
    differentLotCount: 'Different Lot Count',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    userManagement: 'User Management',
    role: 'Role',
    
    // Supplier
    supplierName: 'Supplier Name',
    addSupplier: 'Add Supplier',
    editSupplier: 'Edit Supplier',
    
    // Lot Intake
    lotIntakeForm: 'Lot Intake Form',
    quality: 'Quality',
    color: 'Color',
    meters: 'Meters',
    entryDate: 'Entry Date',
    supplier: 'Supplier',
    warehouseLocation: 'Warehouse Location',
    notes: 'Notes',
    addLot: 'Add Lot',
    creatingLot: 'Creating Lot',
    createLot: 'Create Lot',
    lotCreatedSuccessMessage: 'Lot created successfully',
    
    // QR Scan Page
    qrCodeScanner: 'QR Code Scanner',
    scanQrCode: 'Scan QR Code',
    startCameraScanning: 'Start Camera Scanning',
    uploadQrImage: 'Upload QR Image',
    uploadImage: 'Upload Image',
    uploadFile: 'Upload File',
    selectLotFrom: 'Select Lot',
    selectLotPlaceholder: 'Choose a lot...',
    generateQr: 'Generate QR',
    quickQrEntry: 'Quick QR Entry',
    qrCodeScanned: 'QR Code Scanned',
    qrCodeGenerated: 'QR Code Generated',
    qrCodeDetectedSuccess: 'QR Code detected successfully!',
    qrCodeDetectedFromImage: 'QR Code detected from image!',
    noQrCodeFound: 'No QR code found in image',
    cameraError: 'Failed to access camera. Please check permissions.',
    generateQrDescription: 'Generate a new QR code for lot entry',
    printQrCode: 'Print QR Code',
    positionQrCode: 'Position QR code within the scanning area',
    howToUse: 'How to Use',
    qrInstructions: [
      'Scan QR codes using your camera or upload an image',
      'Select a lot from the dropdown to view details',
      'Generate new QR codes for lot intake',
      'Print QR codes for physical labeling'
    ],
    pleaseLogin: 'Please log in to view lot details',
    signInToView: 'Sign In to View',
    lotNotFound: 'Lot {lotNumber} not found',
    failedToFetch: 'Failed to fetch lot details',
    oldLotWarning: 'This lot is {days} days old. Consider checking quality.',
    age: 'Age',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    partiallyFulfilled: 'Partially Fulfilled',
    intakeQuality: 'Quality',
    intakeColor: 'Color',
    lotIntakeNumber: 'LOT Number',
    
    // Order Queue
    orderQueueManagement: 'Order Queue Management',
    
    // User Management
    createUser: 'Create User',
    editUser: 'Edit User',
    
    // Field Labels
    emailField: 'Email',
    passwordField: 'Password',
    roleField: 'Role',
    fullNameField: 'Full Name',
    
    // Role Options
    adminRole: 'Admin',
    seniorManagerRole: 'Senior Manager',
    accountingRole: 'Accounting',
    warehouseStaffRole: 'Warehouse Staff',
    
    // Permissions
    permissions: 'Permissions',
    permReceiveIncoming: 'Receive Incoming Stock',
    permUnreceiveIncoming: 'Unreceive Incoming Stock',
    permDeleteIncoming: 'Delete Incoming Stock Entry',
    
    // Inventory
    allQualities: 'All Qualities',
    physicalLots: 'Physical Lots',
    physicalMeters: 'Physical Meters',
    physicalRolls: 'Physical Rolls',
    incomingMeters: 'Incoming Meters',
    reservedMeters: 'Reserved Meters',
    availableMeters: 'Available Meters',
    
    // Incoming Stock
    totalIncomingMeters: 'Total Incoming Meters',
    awaitingArrival: 'Awaiting Arrival',
    inProgress: 'In Progress',
    pastExpectedDate: 'Past Expected Date',
    allStatusFilter: 'All Status',
    allSuppliers: 'All Suppliers',
    incomingStockEntries: 'Incoming Stock Entries',
    partiallyReceived: 'Partially Received',
    fullyReceived: 'Fully Received',
    filterBySupplier: 'Filter by Supplier',
    filterByStatus: 'Filter by Status',
    pendingInbound: 'Pending Inbound',
    partial: 'Partial',
    complete: 'Complete',
    receive: 'Receive',
    open: 'Open',
    progressLabel: 'Progress',
    arrivalDate: 'Arrival Date',
    invoiceNumber: 'Invoice Number',
    newEntry: 'New Entry',
    noIncomingStockFound: 'No incoming stock found',
    failedToFetchIncomingStock: 'Failed to fetch incoming stock',
    noPermissionIncomingStock: 'You do not have permission to view incoming stock',
    loadingEllipsis: 'Loading...',
    
    // Audit Log
    auditLog: 'Audit Log',
    actionHistory: 'Action History',
    user: 'User',
    action: 'Action',
    timestamp: 'Timestamp',
    description: 'Description',
    entity: 'Entity',
    identifier: 'Identifier',
    reversed: 'Reversed',
    auditActions: 'Actions',
    fulfill: 'Fulfill',
    refresh: 'Refresh',
    
    // Audit Detail Keys
    auditOrderNumber: 'Order Number:',
    auditCustomer: 'Customer:',
    auditLot: 'Lot',
    auditRollsCount: 'rolls',
    auditTotalRolls: 'Total Rolls:',
    auditLots: 'Lots:',
    auditFulfilled: 'Fulfilled:',
    auditLotNumber: 'Lot Number:',
    auditQuality: 'Quality:',
    auditColor: 'Color:',
    auditMeters: 'Meters:',
    auditRollCount: 'Roll Count:',
    auditLocation: 'Location:',
    auditSupplier: 'Supplier:',
    auditEntryDate: 'Entry Date:',
    auditInvoice: 'Invoice:',
    auditRollPosition: 'Roll Position:',
    auditStatus: 'Status:',
    auditSupplierName: 'Supplier Name:',
    auditEmail: 'Email:',
    auditName: 'Name:',
    auditRole: 'Role:',
    auditActive: 'Active',
    auditInactive: 'Inactive',
    detailsNotAvailable: 'Details not available',
    empty: 'Empty',
    yes: 'Yes',
    no: 'No',
    errorFetchingReversalReason: 'Error fetching reversal reason',
    loadingReason: 'Loading reason...',
    reason: 'Reason:',
    noFieldsChanged: 'No fields were changed',
    failedToLoadAuditLogs: 'Failed to load audit logs',
    thisActionWasReversed: 'This action was reversed',
    reversedAt: 'Reversed At:',
    previousState: 'Previous State',
    createdWith: 'Created With',
    newState: 'New State',
    changesMade: 'Changes Made',
    viewTechnicalDetails: 'View Technical Details',
    oldDataJson: 'Old Data (JSON)',
    newDataJson: 'New Data (JSON)',
    reasonForReversal: 'Reason for Reversal',
    enterReasonForReversal: 'Enter reason for reversal...',
    reversing: 'Reversing...',
    reverseActionButton: 'Reverse Action',
    
    // Settings
    settings: 'Settings',
    languageSettings: 'Language Settings',
    
    // Actions
    saveChanges: 'Save Changes',
    
    // Placeholders
    enterEmail: 'Enter email',
    enterPassword: 'Enter password',
    enterFullName: 'Enter full name',
    selectRole: 'Select role',
    
    // Validation Messages
    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',
    fullNameRequired: 'Full name is required',
    roleRequired: 'Role is required',
    
    // Success Messages
    userCreatedSuccessfully: 'User created successfully',
    userUpdatedSuccessfully: 'User updated successfully',
    
    // Error Messages
    failedToCreateUser: 'Failed to create user',
    failedToUpdateUser: 'Failed to update user',
    
    // Confirmation Messages
    confirmDeleteUser: 'Are you sure you want to delete this user?',
    
    // Button Labels
    createUserButton: 'Create User',
    updateUserButton: 'Update User',
    deleteUserButton: 'Delete User',
    
    // Table Headers
    idHeader: 'ID',
    emailHeader: 'Email',
    fullNameHeader: 'Full Name',
    roleHeader: 'Role',
    actionsHeader: 'Actions',
    
    // Admin Dashboard
    totalUsers: 'Total Users',
    activeLots: 'Active Lots',
    pendingOrders: 'Pending Orders',
    
    // Admin Dashboard Descriptions
    totalUsersDescription: 'Number of registered users',
    activeLotsDescription: 'Number of active lots in the system',
    pendingOrdersDescription: 'Number of orders currently pending',
    
    // Admin Dashboard Cards
    usersCardTitle: 'Users',
    lotsCardTitle: 'Lots',
    ordersCardTitle: 'Orders',
    
    // Admin Dashboard Button
    manageUsersButton: 'Manage Users',
    manageLotsButton: 'Manage Lots',
    manageOrdersButton: 'Manage Orders',
    
    // Admin Dashboard Section Titles
    systemOverview: 'System Overview',
    userActivity: 'User Activity',
    
    // Admin Dashboard Placeholders
    noActivityPlaceholder: 'No user activity to display',
    
    // Admin Dashboard Labels
    lastLoginLabel: 'Last Login',
    
    // Admin Dashboard Messages
    welcomeAdmin: 'Welcome, Admin!',
    
    // Admin Dashboard Tooltips
    viewUserDetailsTooltip: 'View user details',
    editUserDetailsTooltip: 'Edit user details',
    deleteUserTooltip: 'Delete user',
    
    // Admin Dashboard Alerts
    userDeletedAlert: 'User deleted successfully',
    
    // Admin Dashboard Confirmations
    confirmUserDeletion: 'Are you sure you want to delete this user?',
    
    // Admin Dashboard Buttons
    confirmDeleteButton: 'Confirm Delete',
    cancelDeleteButton: 'Cancel Delete',
    
    // Admin Dashboard Forms
    editUserFormTitle: 'Edit User',
    createUserFormTitle: 'Create User',
    
    // Admin Dashboard Inputs
    emailInputLabel: 'Email',
    passwordInputLabel: 'Password',
    fullNameInputLabel: 'Full Name',
    roleSelectLabel: 'Role',
    
    // Admin Dashboard Select Options
    adminRoleOption: 'Admin',
    managerRoleOption: 'Manager',
    staffRoleOption: 'Staff',
    
    // Admin Dashboard Buttons
    submitFormButton: 'Submit',
    cancelFormButton: 'Cancel',
    
    // Admin Dashboard Messages
    userCreatedMessage: 'User created successfully',
    userUpdatedMessage: 'User updated successfully',
    
    // Admin Dashboard Errors
    createUserError: 'Failed to create user',
    updateUserError: 'Failed to update user',
    
    // Admin Dashboard Placeholders
    enterEmailPlaceholder: 'Enter email',
    enterPasswordPlaceholder: 'Enter password',
    enterFullNamePlaceholder: 'Enter full name',
    selectRolePlaceholder: 'Select role',
    
    // Admin Dashboard Validation
    emailValidationMessage: 'Please enter a valid email',
    passwordValidationMessage: 'Password must be at least 6 characters',
    fullNameValidationMessage: 'Please enter your full name',
    roleValidationMessage: 'Please select a role',
    
    // Admin Dashboard Validation
    emailValidationMessageText: 'Please enter a valid email',
    passwordValidationMessageText: 'Password must be at least 6 characters',
    fullNameValidationMessageText: 'Please enter your full name',
    roleValidationMessageText: 'Please select a role',
    
    // Dashboard Component Keys
    welcomeBack: 'Welcome Back',
    inStockLotsAvailable: 'In-stock lots available',
    totalRollsInventory: 'Total rolls in inventory',
    totalMetersInventory: 'Total meters in inventory',
    awaitingFulfillment: 'Awaiting fulfillment',
    expectedMetersPendingReceipt: 'Expected meters pending receipt',
    reservedStock: 'Reserved Stock',
    reservedStockCount: 'active reservations',
    shipmentsAwaitingGoodsReceipt: 'Shipments awaiting goods receipt',
    generateQrCodes: 'Generate QR Codes',
    generateQrCodesDesc: 'Create new lot entries with QR codes',
    goToLotIntake: 'Go to LOT Intake',
    scanQrCodes: 'Scan QR Codes',
    scanQrCodesDesc: 'Scan existing QR codes for lot management',
    goToQrScanner: 'Go to QR Scanner',
    fulfillOrders: 'Fulfill Orders',
    fulfillOrdersDesc: 'Process and fulfill customer orders',
    goToOrders: 'Go to Orders',
    reviewApprovals: 'Review Approvals',
    reviewApprovalsDesc: 'Approve or reject pending changes',
    goToApprovals: 'Go to Approvals',
    viewReports: 'View Reports',
    viewReportsDesc: 'Access analytics and reports',
    goToReports: 'Go to Reports',
    
    // Layout/Navigation Keys
    approvalRequests: 'Approval Requests',
    viewAsRole: 'View as Role',
    currentRole: '(Current)',
    returnToAdminView: 'Return to Admin View',
    
    // ApprovalQueue Component Keys
    approved: 'Approved',
    rejected: 'Rejected',
    lotApprovedToast: 'approved',
    lotRejectedToast: 'rejected',
    orderApprovedToast: 'Order approved successfully',
    orderRejectedToast: 'Order rejected successfully',
    approvalPermissionDenied: 'You do not have permission to view approvals',
    approvalQueues: 'Approval Queues',
    pendingCount: 'pending',
    inventoryChanges: 'Inventory Changes',
    orderChanges: 'Order Changes',
    pendingInventoryChanges: 'Pending Inventory Changes',
    noPendingInventoryChanges: 'No pending inventory changes',
    pendingOrderChanges: 'Pending Order Changes',
    noPendingOrderChanges: 'No pending order changes',
    submitted: 'Submitted',
    submittedBy: 'Submitted By',
    orderId: 'Order ID',
    approve: 'Approve',
    rejectItem: 'Reject',
    rejectionReason: 'Rejection Reason',
    rejectionReasonPlaceholder: 'Explain why this change is being rejected...',
    
    // FloatingPOCart Component Keys
    cart: 'Cart',
    poCart: 'PO Cart',
    clearAll: 'Clear All',
    qualityColors: 'Quality/Colors',
    lot: 'Lot',
    lots: 'Lots',
    sample: 'Sample',
    daysOld: 'days old',
    addMoreColors: 'Add More Colors',
    addDifferentQuality: 'Add Different Quality',
    
    // HierarchicalAutocomplete Component Keys
    days: 'days',
    rollsLabel: 'rolls',
    seeRolls: 'See Rolls',
    loadingQualities: 'Loading qualities...',
    noQualitiesFound: 'No qualities found.',
    
    // ReservationDialog Component Keys
    selectScope: 'Select Scope',
    selectItems: 'Select Items',
    qualityColorFilter: 'Quality/Color Filter',
    availableQualityColors: 'Available Quality and Colors',
    selectQualityColor: 'Select Quality and Color',
    metersToReserve: 'Meters to Reserve',
    selectRolls: 'Select Rolls',
    rollSelection: 'Roll Selection',
    selectedRollsMeterTotal: 'Selected Rolls (Total Meters)',
    reservationLines: 'Reservation Lines',
    removeLineItem: 'Remove Line Item',
    createReservation: 'Create Reservation',
    reservationCreatedNote: 'Created reservation {reservationNumber} for {customerName}',
    customerName: 'Customer Name',
    
    // ReservationDetailsDialog Component Keys
    reservationMetadata: 'Reservation Metadata',
    location: 'Location',
    convertedToOrder: 'Converted to Order',
    cancelationWarning: 'Canceling this reservation will release all reserved stock back to available inventory',
    selectCancellationReason: 'Select a cancellation reason',
    incomingStockWarning: 'Incoming Stock Lines Cannot Be Converted',
    incomingStockNote: 'The following reservation lines are from incoming stock and will NOT be included in the order',
    availableForConversion: 'Available for Conversion',
    
    // ReservationConvertDialog Component Keys
    inventoryLinesWillConvert: 'The following {count} inventory line(s) will be converted to an order',
    totalMetersToConvert: 'Total meters to convert',
    confirmCustomerName: 'Confirm customer name for the order',
    customerNamePlaceholder: 'Enter customer name...',
    orderPreview: 'Order Preview',
    lineItemsToCreate: 'Line items that will be created',
    
    // Global/Common Keys
    accessDenied: 'Access Denied',
    requiresApprovalPermissions: 'You require approval permissions to view this page',
    approvals: 'Approvals',
    auditLogs: 'Audit Logs',
    reservations: 'Reservations',
    canceled: 'Canceled',
    released: 'Released',
    
    // Dashboard Quick Actions - Accounting Role
    receiveGoodsAction: 'Receive Goods',
    receiveGoodsDesc: 'Process incoming shipments and update inventory',
    goToGoodsReceipt: 'Go to Goods Receipt',
    manageReservationsAction: 'Manage Reservations',
    manageReservationsDesc: 'View and manage stock reservations',
    goToReservations: 'Go to Reservations',
    trackIncomingStockAction: 'Track Incoming Stock',
    trackIncomingStockDesc: 'Monitor expected shipments and deliveries',
    goToIncomingStock: 'Go to Incoming Stock',
    
    // Dashboard Quick Actions - Senior Manager Role
    viewIncomingStockAction: 'View Incoming Stock',
    viewIncomingStockDesc: 'Review expected inventory shipments',
    
    // Dashboard Quick Actions - Admin Role
    manageSuppliers: 'Manage Suppliers',
    addEditManageSupplier: 'Add, edit, and manage supplier information',
    goToSuppliers: 'Go to Suppliers',
    deleteLots: 'Delete Lots',
    removeLotsFromSystem: 'Remove lots from the system',
    goToInventory: 'Go to Inventory',
    reprintQrCodes: 'Reprint QR Codes',
    regenerateAndPrintQr: 'Regenerate and print QR codes for lots',
    
    // Lot Queue
    lotQueueDescription: 'Complete lot information for pending entries',
    pendingLots: 'Pending Lots',
    allLotsCompleted: 'All lots have been completed and moved to inventory',
    completeLotInfo: 'Complete Lot Information',
    moveToInventory: 'Move to Inventory',
    validationError: 'Validation Error',
    fillRequiredFields: 'Please fill in all required fields',
    lotMovedSuccess: 'LOT moved to inventory successfully',
    noPermissionPage: 'You don\'t have permission to access this page.',
    selectSupplierPlaceholder: 'Select a supplier',
    invoiceNumberPlaceholder: 'e.g., INV-2024-001',
    additionalNotesPlaceholder: 'Additional notes...',
    pendingBadge: 'Pending',
    
    // Lot Intake - Single Entry
    newLotEntry: 'New LOT Entry',
    singleEntryDescription: 'Create a single lot entry with QR code generation',
    intakeSupplier: 'Supplier',
    optionalFields: 'Optional Fields (recommended)',
    
    // Lot Intake - Bulk Import
    bulkImportInstructions: 'Upload a CSV file to import multiple lots at once. Download the template for the correct format.',
    downloadTemplate: 'Download Template',
    importFile: 'Import File',
    importing: 'Importing',
    progress: 'Progress',
    importResults: 'Import Results',
    failed: 'Failed',
    errorsFound: 'Errors Found',
    downloadErrorReport: 'Download Error Report',
    parsingErrors: 'Parsing Errors',
    rowError: 'Row',
    moreParsingErrors: 'more parsing errors',
    databaseErrors: 'Database Errors',
    moreDatabaseErrors: 'more database errors',
    validatingData: 'Validating data',
    processingFile: 'Processing file',
    importStarted: 'Import started',
    selectFileToImport: 'Please select a file to import',
    importError: 'Import Error',
    validationFailed: 'Validation Failed',
    errorsFoundInFile: 'errors found in file',
    
    // Incoming Bulk Upload Dialog
    bulkUploadIncomingStock: 'Bulk Upload Incoming Stock',
    uploadExcelCsv: 'Upload Excel/CSV File',
    template: 'Template',
    upload: 'Upload',
    items: 'Items',
    validStatus: 'Valid',
    successParsedItems: 'Parsed {count} items from file',
    noValidItems: 'No valid items to upload',
    uploadedSuccessfully: 'Successfully uploaded {count} incoming stock entries',
    failedToParseFile: 'Failed to parse file. Please check format.',
    supplierNotFound: 'Supplier "{name}" not found in system',
    invoiceNumberRequired: 'Invoice number is required',
    invalidInvoiceDate: 'Invalid invoice date format (use YYYY-MM-DD)',
    invalidArrivalDate: 'Invalid arrival date format (use YYYY-MM-DD)',
    qualityRequired: 'Quality is required',
    colorRequired: 'Color is required',
    metersMustBePositive: 'Expected meters must be greater than 0',
    foundItems: 'Found {total} items: {valid} valid, {errors} with errors',
    
    // Order Queue Page
    orderApprovalQueue: 'Order Approval Queue',
    pendingApprovals: 'Pending Approvals',
    pendingUppercase: 'Pending',
    processedUppercase: 'Processed',
    noOrdersPendingApproval: 'No orders pending approval',
    orderHash: 'Order #',
    totalRolls: 'Total Rolls',
    review: 'Review',
    orderDetails: 'Order Details',
    customerLabel: 'Customer',
    submittedAtLabel: 'Submitted At',
    orderLots: 'Order Lots',
    ageDays: 'Age (days)',
    rejectionReasonOptional: 'Rejection Reason (optional)',
    enterReasonForRejection: 'Enter reason for rejection...',
    recentlyProcessed: 'Recently Processed',
    rejectionReasonTitle: 'Rejection Reason',
    orderApprovedSuccessfully: 'Order approved successfully',
    orderRejected: 'Order rejected',
    failedToProcessApproval: 'Failed to process approval',
    noPermissionOrderQueue: "You don't have permission to access the order queue. Contact your administrator.",
    
    // Approval Queue - Field Changes
    fieldChanges: 'Field Changes',
    pendingFieldChanges: 'Pending Field Changes',
    noPendingFieldChanges: 'No pending field changes',
    table: 'Table',
    fieldChangeApproved: 'Field change for {field} has been approved',
    fieldChangeRejected: 'Field change for {field} has been rejected',
    
    // Supplier Management Page
    supplierManagement: 'Supplier Management',
    totalSuppliers: 'Total Suppliers',
    activeSuppliersInSystem: 'Active suppliers in system',
    noSuppliersFound: 'No suppliers found. Add your first supplier to get started.',
    addNewSupplier: 'Add New Supplier',
    supplierNameLabel: 'Supplier Name',
    enterSupplierName: 'Enter supplier name',
    supplierNameRequired: 'Supplier name is required.',
    supplierUpdatedSuccessfully: 'Supplier updated successfully.',
    supplierCreatedSuccessfully: 'Supplier created successfully.',
    failedToSaveSupplier: 'Failed to save supplier.',
    confirmDeleteSupplier: 'Are you sure you want to delete this supplier?',
    supplierDeletedSuccessfully: 'Supplier deleted successfully.',
    failedToDeleteSupplier: 'Failed to delete supplier. It may be associated with existing lots.',
    notAuthorizedSuppliers: 'You are not authorized to access suppliers.',
    
    // Admin Panel - User Management
    adminPanel: 'Admin Panel',
    addUser: 'Add User',
    activeSystemUsers: 'Active system users',
    admins: 'Admins',
    administratorAccounts: 'Administrator accounts',
    seniorManagers: 'Senior Managers',
    seniorManagersDesc: 'Management level users',
    accountingUsers: 'Accounting users',
    inviteNewUsers: 'Invite New Users',
    sendInvitationsToNewMembers: 'Send invitations to new team members',
    reconcilingUsers: 'Reconciling...',
    reconcileUsers: 'Reconcile Users',
    enterEmailAddress: 'Enter email address',
    sendInvitation: 'Send Invitation',
    sending: 'Sending...',
    pendingInvitations: 'Pending Invitations',
    usersInvitedNotAccepted: 'Users who have been invited but haven\'t accepted yet',
    noPendingInvitations: 'No pending invitations',
    emailStatus: 'Email Status',
    invited: 'Invited',
    emailSentSuccessfully: 'Email sent successfully',
    provideEmailAndRole: 'Please provide email and role',
    invalidEmail: 'Invalid Email',
    enterValidEmail: 'Please enter a valid email address',
    userAlreadyExists: 'User Already Exists',
    emailAlreadyRegistered: 'This email is already registered. Edit the existing user instead.',
    invitationSentSuccessfully: 'Invitation sent successfully via email',
    invitationDeleted: 'Invitation for {email} has been deleted',
    failedToDeleteInvitation: 'Failed to delete invitation',
    errorFetchingProfiles: 'Failed to fetch user profiles',
    profileUpdatedSuccessfully: 'Profile updated successfully',
    failedToUpdateProfile: 'Failed to update profile',
    userDeletedSuccessfully: 'User {name} deleted successfully',
    failedToDeleteUser: 'Failed to delete user',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordMustBe8Chars: 'Password must be at least 8 characters long',
    passwordChangedSuccessfully: 'Password changed successfully',
    failedToChangePassword: 'Failed to change password',
    passwordTooWeak: 'Password is too weak. Please use a stronger password.',
    passwordCompromised: 'This password has appeared in data breaches. Please use a different one.',
    reconciliationComplete: 'Reconciliation Complete',
    reconciliationFailed: 'Reconciliation Failed',
    invitationResent: 'Invitation Resent',
    invitationResentTo: 'Invitation resent to {email}',
    resendFailed: 'Resend Failed',
    failedToResendInvitation: 'Failed to resend invitation',
    copied: 'Copied',
    invitationLinkCopied: 'Invitation link copied to clipboard',
    notAuthorizedAccess: 'You are not authorized to access this page',
    
    // Dashboard Statistics (additional)
    totalLots: 'Total Lots',
    totalMeters: 'Total Meters',
    pendingReceipts: 'Pending Receipts',
    totalOrders: 'Total Orders',
    
    // Lot Intake - Additional
    singleLotEntry: 'Single LOT Entry',
    bulkLotImport: 'Bulk LOT Import',
    rollCount: 'Roll Count',
    invoiceDate: 'Invoice Date',
    productionDate: 'Production Date',
    
    // Incoming Stock - Enhanced
    expectedStockOnTheWay: 'Expected stock on the way',
    activeReservations: 'Active Reservations',
    physicalPlusIncomingMinusReserved: 'Physical + Incoming - Reserved',
    incoming: 'Incoming',
    available: 'Available',
    pendingShipments: 'Pending Shipments',
    totalPendingMeters: 'Total Pending Meters',
    expectedToday: 'Expected Today',
    invoice: 'Invoice',
    expected: 'Expected',
    received: 'Received',
    remaining: 'Remaining',
    overdue: 'Overdue',
    pending: 'Pending',
    
    // Goods Receipt - Unreceive and Delete functionality
    unreceiveStock: 'Unreceive Stock',
    deleteIncomingStock: 'Delete Incoming Stock',
    deleteIncomingStockTitle: 'Delete Incoming Stock Entry',
    deleteIncomingStockDesc: 'Delete incoming stock entry for {quality} - {color}',
    deleteIncomingStockWarning: 'This will permanently remove this pending stock entry',
    noStockReceived: 'No stock has been received yet',
    stockPartiallyReceived: 'Warning: {received}m has already been received',
    cannotDeleteReceived: 'Cannot delete: Stock has been partially or fully received. Please unreceive first.',
    cannotDeleteReserved: 'Cannot delete: {reserved}m is reserved',
    deleteIncomingStockButton: 'Delete Entry',
    deleting: 'Deleting...',
    incomingStockDeleted: 'Incoming stock entry deleted successfully',
    deletedIncomingStockNote: 'Deleted incoming stock entry: {invoice} - {quality}/{color} ({meters}m expected)',
    unreceiveStockTitle: 'Unreceive Stock',
    unreceiveStockDesc: 'Unreceive goods receipt for {quality} - {color}',
    selectLotsToUnreceive: 'Select Lots to Unreceive',
    unreceivingWillDelete: 'Unreceiving will delete the selected lots, rolls, and receipt records',
    cannotUnreceiveOrdered: 'Cannot unreceive: Rolls from this lot are in orders',
    cannotUnreceiveReserved: 'Cannot unreceive: Rolls from this lot are reserved',
    unreceiveButton: 'Unreceive Selected',
    unreceiving: 'Unreceiving...',
    stockUnreceivedSuccess: 'Stock unreceived successfully',
    selectAtLeastOneLot: 'Please select at least one lot to unreceive',
    lotsFromThisReceipt: 'Lots from this receipt',
    selectAll: 'Select All',
    noLotsFound: 'No lots found for this incoming stock entry',
    
    // Admin Panel - Additional Keys
    fullName: 'Full Name',
    addNewUser: 'Add New User',
    
    // Role Labels (for PermissionsTab and Admin)
    roleWarehouseStaff: 'Warehouse Staff',
    roleDescWarehouseStaff: 'Handle inventory, QR codes, and order fulfillment',
    roleAccounting: 'Accounting',
    roleDescAccounting: 'Manage orders, incoming stock, and reservations',
    roleSeniorManager: 'Senior Manager',
    roleDescSeniorManager: 'Approve changes and access reports',
    roleAdmin: 'Admin',
    roleDescAdmin: 'Full system access and user management',
    
    // Permissions Tab
    permissionsTitle: 'Role Permissions Matrix',
    resetToDefaults: 'Reset to Defaults',
    saving: 'Saving...',
    permissionsUpdatedSuccessfully: 'Permissions updated successfully',
    failedToSavePermissions: 'Failed to save permissions',
    failedToLoadPermissions: 'Failed to load permissions',
    tableHeaderAction: 'Action',
    tableHeaderWarehouseStaff: 'Warehouse Staff',
    tableHeaderAccounting: 'Accounting',
    tableHeaderSeniorManager: 'Senior Manager',
    tableHeaderAdmin: 'Admin',
    
    // Categories
    categoryUserManagement: 'User Management',
    categoryInventory: 'Inventory Management',
    categoryOrders: 'Order Management',
    categorySuppliers: 'Supplier Management',
    categoryReports: 'Reporting & Analytics',
    categoryQrDocuments: 'QR Code & Document Management',
    categoryApprovals: 'Approvals (Change Requests)',
    categoryAuditLogs: 'Audit Logs',
    
    // User Management Actions
    actionViewUsers: 'View Users',
    actionCreateUsers: 'Create Users',
    actionEditUsers: 'Edit Users',
    actionDeleteUsers: 'Delete Users',
    actionManageRoles: 'Manage Roles',
    actionChangePermissions: 'Change Permissions',
    
    // Inventory Management Actions
    actionViewInventory: 'View Inventory',
    actionCreateLotEntries: 'Create LOT Entries',
    actionEditLotInfo: 'Edit LOT Information',
    actionDeleteLotEntries: 'Delete LOT Entries',
    actionGenerateQrCodes: 'Generate QR Codes',
    actionViewIncoming: 'View Incoming Stock',
    actionReceiveIncoming: 'Receive Incoming Stock',
    actionUnreceiveIncoming: 'Unreceive Incoming Stock',
    actionDeleteIncoming: 'Delete Incoming Stock Entry',
    
    // Order Actions
    actionViewOrders: 'View Orders',
    actionCreateOrders: 'Create Orders',
    actionEditOrders: 'Edit Orders',
    actionDeleteOrders: 'Delete Orders',
    actionFulfillOrders: 'Fulfill Orders',
    actionPrintOrderDocs: 'Print Order Documents',
    
    // Supplier Actions
    actionViewSuppliers: 'View Suppliers',
    actionCreateSuppliers: 'Create Suppliers',
    actionEditSuppliers: 'Edit Suppliers',
    actionDeleteSuppliers: 'Delete Suppliers',
    
    // Reports Actions
    actionViewReports: 'View Reports',
    actionExportReports: 'Export Reports',
    actionAccessDashboard: 'Access Dashboard',
    
    // QR & Documents Actions
    actionScanQrCodes: 'Scan QR Codes',
    actionPrintLotLabels: 'Print LOT Labels',
    actionBulkQrGeneration: 'Bulk QR Generation',
    
    // Approvals Actions
    actionViewApprovals: 'View Approvals',
    actionApproveChanges: 'Approve Changes',
    actionRejectChanges: 'Reject Changes',
    
    // Audit Logs Actions
    actionViewOwnLogs: 'View Own Logs',
    actionViewAllLogs: 'View All Logs',
    actionReverseActions: 'Reverse Actions',
  },
  tr: {
    // Navigation
    dashboard: 'Panel',
    lotIntake: 'LOT Girişi',
    inventory: 'Envanter',
    orders: 'Siparişler',
    qrScan: 'QR Tarama',
    orderQueue: 'Sipariş Sırası',
    reports: 'Raporlar',
    suppliers: 'Tedarikçiler',
    admin: 'Yönetici',
    signOut: 'Çıkış Yap',

    // Navigation and sections
    overview: 'Genel Bakış',
    inventoryManagement: 'Stok Yönetimi',
    incomingStockLabel: 'Yoldaki Envanter',
    goodsReceipt: 'Gelen Envanteri Stoğa Al',
    ordersAndReservations: 'Siparişler ve Rezerveler',
    toolsAndUtilities: 'Araçlar',
    reportsAndAdmin: 'Raporlar ve Yönetici',
    
    // Inventory Stats
    physicalLots: 'Fiziki Lot Sayısı',
    physicalMeters: 'Fiziksel Olarak Mevcut Metraj',
    physicalRolls: 'Fiziksel Mevcut Top Sayısı',
    incomingMeters: 'Yoldaki Metraj',
    expectedStockOnTheWay: 'Yolda gelmesi beklenen metraj',
    reservedMeters: 'Rezerve Metraj',
    activeReservations: 'Aktif Rezervasyonlar',
    availableMeters: 'Satılabilir Toplam Metraj',
    physicalPlusIncomingMinusReserved: 'Fiziki + Yoldaki - Rezerve',
    incoming: 'Yolda',
    reserved: 'Rezerve',
    available: 'Satılabilir',
    
    // Goods Receipt
    pendingShipments: 'Bekleyen Gönderiler',
    totalPendingMeters: 'Gönderim Bekleyen Metraj',
    expectedToday: 'Bugüne Beklenen',
    overdue: 'Tarihi Geçmiş',
    pendingReceipts: 'Stoğa Alınmayı Bekleyen',
    receiptHistory: 'Stoğa Alınma Geçmişi',
    pending: 'Beklemede',
    invoice: 'Fatura:',
    expected: 'Beklenen:',
    received: 'Gelen:',
    remaining: 'Kalan:',
    receiveStock: 'Stoğa al',
    
    // Incoming Stock
    totalIncomingMeters: 'Toplam Yoldaki Metraj',
    awaitingArrival: 'Gelmesi Bekleniyor',
    inProgress: 'Devam Ediyor',
    pastExpectedDate: 'Tarihi Geçmiş',
    allStatusFilter: 'Tüm Durumlar',
    allSuppliers: 'Tüm Tedarikçiler',
    incomingStockEntries: 'Yoldaki Envanter Kayıtları',
    partiallyReceived: 'Kısmen Alındı',
    fullyReceived: 'Tamamen Alındı',
    filterBySupplier: 'Tedarikçiye Göre Filtrele',
    filterByStatus: 'Duruma Göre Filtrele',
    pendingInbound: 'Gelmesi Bekleniyor',
    partial: 'Kısmi',
    complete: 'Tamamlandı',
    receive: 'Al',
    open: 'Açık',
    progressLabel: 'İlerleme',
    arrivalDate: 'Varış Tarihi',
    invoiceNumber: 'Fatura Numarası',
    newEntry: 'Yeni Giriş',
    noIncomingStockFound: 'Yoldaki envanter bulunamadı',
    failedToFetchIncomingStock: 'Yoldaki envanter getirilemedi',
    confirmDeleteIncomingStock: 'Bu yoldaki envanteri silmek istediğinizden emin misiniz?',
    incomingStockDeletedSuccess: 'Yoldaki envanter başarıyla silindi',
    failedToDeleteIncomingStock: 'Yoldaki envanter silinemedi',
    noPermissionIncomingStock: 'Yoldaki envanteri görüntüleme izniniz yok',
    loadingEllipsis: 'Yükleniyor...',
    
    // Goods Receipt - Unreceive/Delete functionality
    unreceiveStock: 'Stoğa Alımı Geri Al',
    deleteIncomingStock: 'Yoldaki Stoğu sil',
    unreceiveTitle: 'Stoğa Alımı Geri Al',
    unreceiveDescription: 'Fatura {invoice} stoğa alımını geri al',
    unreceiveInfo: 'Bu işlem bu faturadan stoğa alınan tüm lotları geri alacaktır',
    lotsWillBeDeleted: '{count} lot silinecek ({quality}, {color}, {meters}m)',
    unreceiveWarning: 'Bu işlem geri alınamaz. Lotlar silinecek ve yoldaki envanter güncellenecektir.',
    unreceiveButton: 'Stoğa Alımı Geri Al',
    unreceiving: 'Geri alınıyor...',
    cannotUnreceiveReserved: 'Rezerve metrajı olan lotlar silinemez. Önce {reserved}m metraj rezervasyonunu iptal edin.',
    unreceiveSuccess: 'Stoğa alım başarıyla geri alındı',
    unreceiveFailed: 'Stoğa alım geri alınamadı',
    noLotsToUnreceive: 'Geri alınacak lot bulunamadı',
    deleteIncomingStockTitle: 'Yoldaki Envanter Kaydını Sil',
    deleteIncomingStockDesc: 'Fatura {invoice} yoldaki envanter kaydını kalıcı olarak sil',
    deleteIncomingWarning: 'Bu işlem geri alınamaz. Kayıt kalıcı olarak silinecektir.',
    deleteIncomingButton: 'Yoldaki Envanteri Sil',
    deleting: 'Siliniyor...',
    deleteIncomingSuccess: 'Yoldaki envanter başarıyla silindi',
    deleteIncomingFailed: 'Yoldaki envanter silinemedi',
    cannotDeleteReceived: 'Kısmen veya tamamen alınmış yoldaki envanter silinemez. Önce stoğa alımı geri alın.',
    cannotDeleteReserved: 'Rezerve metrajı olan yoldaki envanter silinemez. Önce {reserved}m metraj rezervasyonunu iptal edin.',
    operationError: 'İşlem Hatası',
    confirmDeletion: 'Silmeyi Onayla',
    keepEntry: 'Kaydı Koru',
    fetchLotsError: 'Lotlar yüklenemedi',
    fetchReceiptsError: 'Alımlar yüklenemedi',
    unreceiveNote: 'Fatura {invoice} için stoğa alım geri alındı - {lotCount} lot silindi ({meters}m)',
    deleteIncomingNote: 'Yoldaki envanter kaydı silindi - Fatura {invoice}, {quality}, {meters}m',
    
    // Reports
    reportsAndAnalytics: 'Raporlar ve Analitik',
    pickDateRange: 'Tarih aralığı seç',
    totalLots: 'Lot Sayısı',
    totalOrders: 'Sipariş Sayısı',
    totalMeters: 'Toplam Metraj',
    totalRolls: 'Toplam Top sayısı',
    totalQualities: 'Toplam Kaliteler',
    lotsByQuality: 'Kalite bazında Lot sayısı',
    orderStatus: 'Siparişi Durumu',
    inventoryAnalysis: 'Envanter Analizi',
    orderPerformance: 'Sipariş Performansı',
    salesReport: 'Satış Raporu',
    supplierAnalysis: 'Tedarikçi Analizi',
    
    // Common
    search: 'Ara',
    filter: 'Filtre',
    export: 'Dışa Aktar',
    save: 'Kaydet',
    cancel: 'İptal',
    edit: 'Düzenle',
    delete: 'Sil',
    create: 'Oluştur',
    update: 'Güncelle',
    loading: 'Yükleniyor...',
    error: 'Hata',
    success: 'Başarılı',
    previous: 'Önceki',
    next: 'Sonraki',
    page: 'Sayfa',
    of: '/',

    // Auth
    email: 'E-posta',
    password: 'Şifre',
    signIn: 'Giriş Yap',
    register: 'Kayıt Ol',
    signOutConfirmation: 'Çıkış yapmak istediğinizden emin misiniz?',
    signOutAction: 'Çıkış Yap',
    
    // Form
    fillAllFields: 'Lütfen tüm alanları doldurun.',
    
    // Orders - specific fields
    allOrders: 'Tüm Siparişler',
    viewManageOrders: 'Mevcut siparişleri görüntüleyin ve yönetin',
    orderNumberField: 'Sipariş Numarası',
    customer: 'Müşteri',
    lotsCount: 'Lot Sayısı',
    status: 'Durum',
    created: 'Oluşturuldu',
    actions: 'Eylemler',
    fulfilled: 'Tamamlandı',
    view: 'Görüntüle',
    print: 'Yazdır',
    orderMarkedFulfilled: 'Sipariş tamamlandı olarak işaretlendi',
    createOrder: 'Sipariş Oluştur',
    standardOrder: 'Standart Sipariş',
    multiQualityOrder: 'Çok Kaliteli Sipariş',
    bulkUpload: 'Toplu Yükleme',
    sampleOrder: 'Numune Siparişi',
    customerNameField: 'Müşteri Adı',
    selectedLots: 'Seçilen Lotlar',
    orderCreatedSuccessfully: 'Sipariş başarıyla oluşturuldu',
    createdOrderNote: '{orderNumber} siparişi {customerName} adına {lotCount} lot, {rollCount} top ve {meters} metre ile oluşturuldu',
    fulfilledOrderNote: '{orderNumber} siparişi {customerName} adına tamamlandı',
    deletedOrderNote: '{orderNumber} siparişi {rollCount} top ile silindi',
    deleteOrder: 'Siparişi Sil',
    confirmDelete: 'Silmeyi Onayla',
    actionCannotBeUndone: 'Bu işlem geri alınamaz.',
    cancelDelete: 'Silmeyi İptal Et',
    noSearchResults: 'Arama sonucu bulunamadı.',
    noInventoryData: 'Envanter verisi bulunamadı.',
    differentColors: 'Farklı Renkler',
    stockOverview: 'Stok Genel Bakışı',
    searchPlaceholder: 'Kaliteye göre ara...',
    viewQuality: 'Kaliteyi Görüntüle',
    deleteMode: 'Silme Modu',
    deleteSelected: 'Seçileni Sil',
    selectForSample: 'Numune İçin Seç',
    rolls: 'toplar',
    
    // Reservation
    newReservation: 'Yeni Rezervasyon',
    reservationNumber: 'Rezervasyon Numarası',
    reservedDate: 'Rezerve Tarihi',
    totalReservedMeters: 'Toplam Rezerve Metre',
    lines: 'Satırlar',
    active: 'Aktif',
    converted: 'Dönüştürüldü',
    reserve: 'Rezerve Et',
    reserveFromIncoming: 'Yoldaki Envanterden Rezerve Et',
    viewReservations: 'Rezervasyonları Görüntüle',
    reservationsForIncoming: 'Yoldaki Envanter Rezervasyonları',
    noReservationsFound: 'Rezervasyon bulunamadı',
    
    // Orders & Reservations
    allReservations: 'Tüm Rezervasyonlar',
    activeReservationsTab: 'Aktif',
    convertedReservationsTab: 'Dönüştürüldü',
    canceledReservationsTab: 'İptal Edildi',
    releasedReservationsTab: 'Serbest Bırakıldı',
    customerId: 'Müşteri No',
    holdUntil: 'Şu Tarihe Kadar Tut',
    releaseReservation: 'Rezervasyonu Serbest Bırak',
    viewDetails: 'Detayları Görüntüle',
    cancelReservation: 'Rezervasyonu İptal Et',
    convertToOrder: 'Siparişe Dönüştür',
    noReservations: 'Rezervasyon bulunamadı',
    createReservationFor: 'Rezervasyon Oluştur',
    physicalInventory: 'Fiziksel Envanter',
    incomingStock: 'Yoldaki Envanter',
    customerInformation: 'Müşteri Bilgileri',
    selectItemsToReserve: 'Rezerve Edilecek Öğeleri Seç',
    selectedItems: 'Seçilen Öğeler',
    totalReservedLabel: 'Toplam Rezerve',
    cancelDialog: 'İptal',
    createReservationButton: 'Rezervasyon Oluştur ({count} öğe)',
    creating: 'Oluşturuluyor...',
    pleaseAddAtLeastOneLine: 'Lütfen en az bir satır ekleyin',
    reservationCreated: 'Rezervasyon başarıyla oluşturuldu',
    optionalCustomerId: 'Müşteri No (Opsiyonel)',
    optionalHoldUntil: 'Şu Tarihe Kadar Tut (Opsiyonel)',
    additionalNotes: 'Ek Notlar (Opsiyonel)',
    totalReserved: 'Toplam Rezerve',
    lineItems: 'Satır Öğeleri',
    reservationDetails: 'Rezervasyon Detayları',
    reservedItems: 'Rezerve Edilen Öğeler',
    scope: 'Kapsam',
    source: 'Kaynak',
    rollsCount: 'Toplar',
    canceledOn: 'İptal Tarihi',
    canceledBy: 'İptal Eden',
    cancelReason: 'İptal Nedeni',
    convertedOn: 'Dönüştürme Tarihi',
    convertedBy: 'Dönüştüren',
    statusHistory: 'Durum Geçmişi',
    closeDialog: 'Kapat',
    releaseStock: 'Stoğu Serbest Bırak',
    cancelReservationTitle: 'Rezervasyonu İptal Et',
    cancelReservationDesc: '{customerName} için {reservationNumber} rezervasyonunu iptal et',
    thisWillReleaseStock: 'Bu tüm rezerve edilmiş stoğu serbest bırakacak',
    metersWillBeReleased: '{meters}m tekrar kullanılabilir olacak',
    cancellationReason: 'İptal Nedeni',
    selectReason: 'Neden seçin',
    customerCanceled: 'Müşteri İptal Etti',
    incorrectEntry: 'Yanlış Giriş',
    noPayment: 'Ödeme Alınmadı',
    otherReason: 'Diğer',
    additionalDetails: 'Ek Detaylar ("Diğer" için Gerekli)',
    explainReason: 'Lütfen nedeni açıklayın...',
    keepReservation: 'Rezervasyonu Koru',
    confirmCancel: 'Rezervasyonu İptal Et',
    canceling: 'İptal Ediliyor...',
    selectCancelReason: 'Lütfen iptal nedeni seçin',
    provideAdditionalDetails: 'Lütfen ek detaylar sağlayın',
    reservationCanceled: 'Rezervasyon başarıyla iptal edildi',
    convertReservationTitle: 'Siparişe Dönüştür',
    convertReservationDesc: '{reservationNumber} rezervasyonunu satış siparişine dönüştür',
    noteIncomingLinesWont: 'Not: Yoldaki satırlar dönüştürülmeyecek',
    incomingLineCount: '{count} yoldaki satır rezervasyonda kalacak',
    inventoryLineWillConvert: '{count} envanter satırı dönüştürülecek',
    leaveEmptyToUse: 'Kullanmak için boş bırakın: {customerName}',
    createOrderButton: 'Sipariş Oluştur',
    creatingOrder: 'Oluşturuluyor...',
    cannotConvert: 'Dönüştürülemiyor: rezervasyon yalnızca yoldaki envanter içeriyor',
    orderCreated: 'Rezervasyondan sipariş başarıyla oluşturuldu',
    releaseReservationTitle: 'Rezervasyonu Serbest Bırak',
    releaseReservationDesc: '{customerName} için {reservationNumber} rezervasyonunu serbest bırak',
    releaseInfo: 'Bu, rezerve edilen stoğu mevcut envantere geri döndürecektir',
    metersWillBeAvailable: '{meters}m tekrar kullanılabilir olacak',
    recordKeepingNote: 'Rezervasyon, kayıt tutma için "Serbest Bırakıldı" durumu ile sistemde kalacaktır.',
    releaseButton: 'Rezervasyonu Serbest Bırak',
    releasing: 'Serbest Bırakılıyor...',
    reservationReleased: 'Rezervasyon başarıyla serbest bırakıldı',
    
    // Audit Logs
    actionCreate: 'Oluştur',
    actionUpdate: 'Güncelle',
    actionDelete: 'Sil',
    actionStatusChange: 'Durum Değişikliği',
    actionFulfill: 'Teslim Et',
    actionApprove: 'Onayla',
    actionReject: 'Reddet',
    lotsEntity: 'Lotlar',
    ordersEntity: 'Siparişler',
    rollsEntity: 'Toplar',
    suppliersEntity: 'Tedarikçiler',
    profilesEntity: 'Profiller',
    lotQueue: 'Lot Kuyruğu',
    fieldEditQueue: 'Alan Düzenleme Kuyruğu',
    rolePermission: 'Rol İzni',
    searchByIdentifierOrUser: 'Tanımlayıcı veya kullanıcıya göre ara...',
    filterByAction: 'Eyleme göre filtrele',
    filterByEntity: 'Varlığa göre filtrele',
    allActions: 'Tüm Eylemler',
    allEntities: 'Tüm Varlıklar',
    actionDetails: 'Eylem Detayları',
    reverseAction: 'Eylemi Geri Al',
    reverseActionConfirm: 'Bu eylemi geri almak istediğinizden emin misiniz?',
    
    // Lot
    lotNumber: 'Lot Numarası',
    differentLotCount: 'Farklı Lot Sayısı',
    
    // Admin
    adminDashboard: 'Yönetici Paneli',
    userManagement: 'Kullanıcı Yönetimi',
    role: 'Rol',
    
    // Supplier
    supplierName: 'Tedarikçi Adı',
    addSupplier: 'Tedarikçi Ekle',
    editSupplier: 'Tedarikçi Düzenle',
    
    // Lot Intake
    lotIntakeForm: 'Lot Giriş Formu',
    quality: 'Kalite',
    color: 'Renk',
    meters: 'Metre',
    entryDate: 'Giriş Tarihi',
    supplier: 'Tedarikçi',
    warehouseLocation: 'Depo Konumu',
    notes: 'Notlar',
    addLot: 'Lot Ekle',
    creatingLot: 'Lot Oluşturuluyor',
    createLot: 'Lot Oluştur',
    lotCreatedSuccessMessage: 'Lot başarıyla oluşturuldu',
    
    // QR Scan Page
    qrCodeScanner: 'QR Kod Tarayıcı',
    scanQrCode: 'QR Kodu Tara',
    startCameraScanning: 'Kamera Taramasını Başlat',
    uploadQrImage: 'QR Görüntüsü Yükle',
    uploadImage: 'Görüntü Yükle',
    uploadFile: 'Dosya Yükle',
    selectLotFrom: 'Lot Seç',
    selectLotPlaceholder: 'Lot seçin...',
    generateQr: 'QR Oluştur',
    quickQrEntry: 'Hızlı QR Girişi',
    qrCodeScanned: 'QR Kod Tarandı',
    qrCodeGenerated: 'QR Kod Oluşturuldu',
    qrCodeDetectedSuccess: 'QR Kod başarıyla algılandı!',
    qrCodeDetectedFromImage: 'Görüntüden QR Kod algılandı!',
    noQrCodeFound: 'Görüntüde QR kod bulunamadı',
    cameraError: 'Kameraya erişilemedi. Lütfen izinleri kontrol edin.',
    generateQrDescription: 'Lot girişi için yeni QR kodu oluştur',
    printQrCode: 'QR Kodunu Yazdır',
    positionQrCode: 'QR kodunu tarama alanı içinde konumlandırın',
    howToUse: 'Nasıl Kullanılır',
    qrInstructions: [
      'Kameranızı kullanarak QR kodlarını tarayın veya bir görüntü yükleyin',
      'Detayları görüntülemek için açılır menüden bir lot seçin',
      'Lot girişi için yeni QR kodları oluşturun',
      'Fiziksel etiketleme için QR kodlarını yazdırın'
    ],
    pleaseLogin: 'Lot detaylarını görüntülemek için lütfen giriş yapın',
    signInToView: 'Görüntülemek İçin Giriş Yapın',
    lotNotFound: 'Lot {lotNumber} bulunamadı',
    failedToFetch: 'Lot detayları getirilemedi',
    oldLotWarning: 'Bu lot {days} gün önce girildi. Kaliteyi kontrol etmeyi düşünün.',
    age: 'Yaş',
    inStock: 'Stokta',
    outOfStock: 'Stok Dışı',
    partiallyFulfilled: 'Kısmen Tamamlandı',
    intakeQuality: 'Kalite',
    intakeColor: 'Renk',
    lotIntakeNumber: 'LOT Numarası',
    scanQRCode: 'QR Kodu Tara',
    
    // Order Queue
    orderQueueManagement: 'Sipariş Sırası Yönetimi',
    
    // User Management
    createUser: 'Kullanıcı Oluştur',
    editUser: 'Kullanıcı Düzenle',
    
    // Field Labels
    emailField: 'E-posta',
    passwordField: 'Şifre',
    roleField: 'Rol',
    fullNameField: 'Ad Soyad',
    
    // Role Options
    adminRole: 'Yönetici',
    seniorManagerRole: 'Üst Düzey Yönetici',
    accountingRole: 'Muhasebe',
    warehouseStaffRole: 'Depo Personeli',
    
    // Permissions
    permissions: 'İzinler',
    permReceiveIncoming: 'Yoldaki Envanteri Al',
    permUnreceiveIncoming: 'Yoldaki Envanteri Geri Al',
    permDeleteIncoming: 'Yoldaki Envanter Kaydını Sil',
    
    // Audit Log
    auditLog: 'Denetim Kaydı',
    actionHistory: 'İşlem Geçmişi',
    user: 'Kullanıcı',
    action: 'Eylem',
    timestamp: 'Zaman Damgası',
    description: 'Açıklama',
    entity: 'Varlık',
    identifier: 'Tanımlayıcı',
    reversed: 'Geri Alındı',
    auditActions: 'Eylemler',
    fulfill: 'Tamamla',
    refresh: 'Yenile',
    
    // Audit Detail Keys
    auditOrderNumber: 'Sipariş Numarası:',
    auditCustomer: 'Müşteri:',
    auditLot: 'Lot',
    auditRollsCount: 'top',
    auditTotalRolls: 'Toplam Top:',
    auditLots: 'Lotlar:',
    auditFulfilled: 'Tamamlandı:',
    auditLotNumber: 'Lot Numarası:',
    auditQuality: 'Kalite:',
    auditColor: 'Renk:',
    auditMeters: 'Metre:',
    auditRollCount: 'Top Sayısı:',
    auditLocation: 'Konum:',
    auditSupplier: 'Tedarikçi:',
    auditEntryDate: 'Giriş Tarihi:',
    auditInvoice: 'Fatura:',
    auditRollPosition: 'Top Pozisyonu:',
    auditStatus: 'Durum:',
    auditSupplierName: 'Tedarikçi Adı:',
    auditEmail: 'E-posta:',
    auditName: 'İsim:',
    auditRole: 'Rol:',
    auditActive: 'Aktif',
    auditInactive: 'Pasif',
    detailsNotAvailable: 'Detaylar mevcut değil',
    empty: 'Boş',
    yes: 'Evet',
    no: 'Hayır',
    errorFetchingReversalReason: 'Geri alma nedeni alınamadı',
    loadingReason: 'Neden yükleniyor...',
    reason: 'Neden:',
    noFieldsChanged: 'Hiçbir alan değiştirilmedi',
    failedToLoadAuditLogs: 'Denetim kayıtları yüklenemedi',
    entityType: 'Varlık Tipi',
    performedBy: 'Yapan',
    thisActionWasReversed: 'Bu işlem geri alındı',
    reversedAt: 'Geri Alınma Zamanı:',
    previousState: 'Önceki Durum',
    createdWith: 'Oluşturuldu',
    newState: 'Yeni Durum',
    changesMade: 'Yapılan Değişiklikler',
    viewTechnicalDetails: 'Teknik Detayları Görüntüle',
    oldDataJson: 'Eski Veri (JSON)',
    newDataJson: 'Yeni Veri (JSON)',
    reasonForReversal: 'Geri Alma Nedeni',
    enterReasonForReversal: 'Geri alma nedenini girin...',
    reversing: 'Geri alınıyor...',
    reverseActionButton: 'İşlemi Geri Al',
    
    // Settings
    settings: 'Ayarlar',
    languageSettings: 'Dil Ayarları',
    
    // Actions
    saveChanges: 'Değişiklikleri Kaydet',
    
    // Placeholders
    enterEmail: 'E-posta girin',
    enterPassword: 'Şifre girin',
    enterFullName: 'Ad soyad girin',
    selectRole: 'Rol seçin',
    
    // Validation Messages
    emailRequired: 'E-posta gerekli',
    passwordRequired: 'Şifre gerekli',
    fullNameRequired: 'Ad soyad gerekli',
    roleRequired: 'Rol gerekli',
    
    // Success Messages
    userCreatedSuccessfully: 'Kullanıcı başarıyla oluşturuldu',
    userUpdatedSuccessfully: 'Kullanıcı başarıyla güncellendi',
    
    // Error Messages
    failedToCreateUser: 'Kullanıcı oluşturulamadı',
    failedToUpdateUser: 'Kullanıcı güncellenemedi',
    
    // Confirmation Messages
    confirmDeleteUser: 'Bu kullanıcıyı silmek istediğinizden emin misiniz?',
    
    // Button Labels
    createUserButton: 'Kullanıcı Oluştur',
    updateUserButton: 'Kullanıcı Güncelle',
    deleteUserButton: 'Kullanıcı Sil',
    
    // Table Headers
    idHeader: 'ID',
    emailHeader: 'E-posta',
    fullNameHeader: 'Ad Soyad',
    roleHeader: 'Rol',
    actionsHeader: 'Eylemler',
    
    // Admin Dashboard
    totalUsers: 'Toplam Kullanıcı',
    activeLots: 'Aktif Lotlar',
    pendingOrders: 'Bekleyen Siparişler',
    
    // Admin Dashboard Descriptions
    totalUsersDescription: 'Kayıtlı kullanıcı sayısı',
    activeLotsDescription: 'Sistemdeki aktif lot sayısı',
    pendingOrdersDescription: 'Şu anda bekleyen sipariş sayısı',
    
    // Admin Dashboard Cards
    usersCardTitle: 'Kullanıcılar',
    lotsCardTitle: 'Lotlar',
    ordersCardTitle: 'Siparişler',
    
    // Admin Dashboard Button
    manageUsersButton: 'Kullanıcıları Yönet',
    manageLotsButton: 'Lotları Yönet',
    manageOrdersButton: 'Siparişleri Yönet',
    
    // Admin Dashboard Section Titles
    systemOverview: 'Sistem Genel Bakışı',
    userActivity: 'Kullanıcı Etkinliği',
    
    // Admin Dashboard Placeholders
    noActivityPlaceholder: 'Görüntülenecek kullanıcı etkinliği yok',
    
    // Admin Dashboard Labels
    lastLoginLabel: 'Son Giriş',
    
    // Admin Dashboard Messages
    welcomeAdmin: 'Hoş Geldiniz, Yönetici!',
    
    // Admin Dashboard Tooltips
    viewUserDetailsTooltip: 'Kullanıcı detaylarını görüntüle',
    editUserDetailsTooltip: 'Kullanıcı detaylarını düzenle',
    deleteUserTooltip: 'Kullanıcıyı sil',
    
    // Admin Dashboard Alerts
    userDeletedAlert: 'Kullanıcı başarıyla silindi',
    
    // Admin Dashboard Confirmations
    confirmUserDeletion: 'Bu kullanıcıyı silmek istediğinizden emin misiniz?',
    
    // Admin Dashboard Buttons
    confirmDeleteButton: 'Silmeyi Onayla',
    cancelDeleteButton: 'Silmeyi İptal Et',
    
    // Admin Dashboard Forms
    editUserFormTitle: 'Kullanıcıyı Düzenle',
    createUserFormTitle: 'Kullanıcı Oluştur',
    
    // Admin Dashboard Inputs
    emailInputLabel: 'E-posta',
    passwordInputLabel: 'Şifre',
    fullNameInputLabel: 'Ad Soyad',
    roleSelectLabel: 'Rol',
    
    // Admin Dashboard Select Options
    adminRoleOption: 'Yönetici',
    managerRoleOption: 'Yönetici',
    staffRoleOption: 'Personel',
    
    // Admin Dashboard Buttons
    submitFormButton: 'Gönder',
    cancelFormButton: 'İptal',
    
    // Admin Dashboard Messages
    userCreatedMessage: 'Kullanıcı başarıyla oluşturuldu',
    userUpdatedMessage: 'Kullanıcı başarıyla güncellendi',
    
    // Admin Dashboard Errors
    createUserError: 'Kullanıcı oluşturulamadı',
    updateUserError: 'Kullanıcı güncellenemedi',
    
    // Admin Dashboard Placeholders
    enterEmailPlaceholder: 'E-posta girin',
    enterPasswordPlaceholder: 'Şifre girin',
    enterFullNamePlaceholder: 'Ad soyad girin',
    selectRolePlaceholder: 'Rol seçin',
    
    // Admin Dashboard Validation
    emailValidationMessage: 'Lütfen geçerli bir e-posta girin',
    passwordValidationMessage: 'Şifre en az 6 karakter olmalı',
    fullNameValidationMessage: 'Lütfen adınızı ve soyadınızı girin',
    roleValidationMessage: 'Lütfen bir rol seçin',
    
    // Admin Dashboard Validation
    emailValidationMessageText: 'Lütfen geçerli bir e-posta girin',
    passwordValidationMessageText: 'Şifre en az 6 karakter olmalı',
    fullNameValidationMessageText: 'Lütfen adınızı ve soyadınızı girin',
    roleValidationMessageText: 'Lütfen bir rol seçin',
    
    // Dashboard Component Keys
    welcomeBack: 'Hoş Geldiniz',
    inStockLotsAvailable: 'Stoktaki mevcut lotlar',
    totalRollsInventory: 'Envanterda toplam top sayısı',
    totalMetersInventory: 'Envanterda toplam metraj',
    awaitingFulfillment: 'Teslim Bekliyor',
    expectedMetersPendingReceipt: 'Teslim alınmayı bekleyen tahmini metraj',
    reservedStock: 'Rezerve Edilmiş Stok',
    reservedStockCount: 'aktif rezervasyon',
    shipmentsAwaitingGoodsReceipt: 'Mal kabul bekleyen gönderiler',
    generateQrCodes: 'QR Kodları Oluştur',
    generateQrCodesDesc: 'QR kodlu yeni lot girişleri oluştur',
    goToLotIntake: 'LOT Girişine Git',
    scanQrCodes: 'QR Kodlarını Tara',
    scanQrCodesDesc: 'Lot yönetimi için mevcut QR kodlarını tara',
    goToQrScanner: 'QR Tarayıcıya Git',
    fulfillOrders: 'Siparişleri Teslim Et',
    fulfillOrdersDesc: 'Müşteri siparişlerini işle ve teslim et',
    goToOrders: 'Siparişlere Git',
    reviewApprovals: 'Onayları İncele',
    reviewApprovalsDesc: 'Bekleyen değişiklikleri onayla veya reddet',
    goToApprovals: 'Onaylara Git',
    viewReports: 'Raporları Görüntüle',
    viewReportsDesc: 'Analitiklere ve raporlara eriş',
    goToReports: 'Raporlara Git',
    
    // Layout/Navigation Keys
    approvalRequests: 'Onay Talepleri',
    viewAsRole: 'Rol Olarak Görüntüle',
    currentRole: '(Mevcut)',
    returnToAdminView: 'Yönetici Görünümüne Dön',
    
    // ApprovalQueue Component Keys
    approved: 'Onaylandı',
    rejected: 'Reddedildi',
    lotApprovedToast: 'onaylandı',
    lotRejectedToast: 'reddedildi',
    orderApprovedToast: 'Sipariş başarıyla onaylandı',
    orderRejectedToast: 'Sipariş başarıyla reddedildi',
    approvalPermissionDenied: 'Onayları görüntüleme izniniz yok',
    approvalQueues: 'Onay Kuyrukları',
    pendingCount: 'beklemede',
    inventoryChanges: 'Envanter Değişiklikleri',
    orderChanges: 'Sipariş Değişiklikleri',
    pendingInventoryChanges: 'Bekleyen Envanter Değişiklikleri',
    noPendingInventoryChanges: 'Bekleyen envanter değişikliği yok',
    pendingOrderChanges: 'Bekleyen Sipariş Değişiklikleri',
    noPendingOrderChanges: 'Bekleyen sipariş değişikliği yok',
    submitted: 'Gönderildi',
    submittedBy: 'Gönderen',
    orderId: 'Sipariş No',
    approve: 'Onayla',
    rejectItem: 'Reddet',
    rejectionReason: 'Reddetme Nedeni',
    rejectionReasonPlaceholder: 'Bu değişikliğin neden reddedildiğini açıklayın...',
    
    // FloatingPOCart Component Keys
    cart: 'Sepet',
    poCart: 'Sipariş Sepeti',
    clearAll: 'Tümünü Temizle',
    qualityColors: 'Kalite/Renkler',
    lot: 'Lot',
    lots: 'Lotlar',
    sample: 'Numune',
    daysOld: 'gün önce',
    addMoreColors: 'Daha Fazla Renk Ekle',
    addDifferentQuality: 'Farklı Kalite Ekle',
    
    // HierarchicalAutocomplete Component Keys
    days: 'gün',
    rollsLabel: 'top',
    seeRolls: 'Topları Gör',
    loadingQualities: 'Kaliteler yükleniyor...',
    noQualitiesFound: 'Kalite bulunamadı.',
    
    // ReservationDialog Component Keys
    selectScope: 'Kapsam Seç',
    selectItems: 'Öğe Seç',
    qualityColorFilter: 'Kalite/Renk Filtresi',
    availableQualityColors: 'Mevcut Kalite ve Renkler',
    selectQualityColor: 'Kalite ve Renk Seç',
    metersToReserve: 'Rezerve Edilecek Metre',
    selectRolls: 'Top Seç',
    rollSelection: 'Top Seçimi',
    selectedRollsMeterTotal: 'Seçilen Toplar (Toplam Metre)',
    reservationLines: 'Rezervasyon Satırları',
    removeLineItem: 'Satırı Kaldır',
    createReservation: 'Rezervasyon Oluştur',
    reservationCreatedNote: '{customerName} için {reservationNumber} rezervasyonu oluşturuldu',
    customerName: 'Müşteri Adı',
    
    // ReservationDetailsDialog Component Keys
    reservationMetadata: 'Rezervasyon Meta Verileri',
    location: 'Konum',
    convertedToOrder: 'Siparişe Dönüştürüldü',
    cancelationWarning: 'Bu rezervasyonu iptal etmek, tüm rezerve edilen stoğu mevcut envantere geri döndürecektir',
    selectCancellationReason: 'İptal nedeni seçin',
    incomingStockWarning: 'Yoldaki Envanter Satırları Dönüştürülemez',
    incomingStockNote: 'Aşağıdaki rezervasyon satırları yoldaki envanterden olup siparişe DAHIL EDİLMEYECEKTİR',
    availableForConversion: 'Dönüştürme İçin Uygun',
    
    // ReservationConvertDialog Component Keys
    inventoryLinesWillConvert: 'Aşağıdaki {count} envanter satırı siparişe dönüştürülecek',
    totalMetersToConvert: 'Dönüştürülecek toplam metraj',
    confirmCustomerName: 'Sipariş için müşteri adını onaylayın',
    customerNamePlaceholder: 'Müşteri adını girin...',
    orderPreview: 'Sipariş Önizlemesi',
    lineItemsToCreate: 'Oluşturulacak satır öğeleri',
    
    // Global/Common Keys
    accessDenied: 'Erişim Reddedildi',
    requiresApprovalPermissions: 'Bu sayfayı görüntülemek için onay izinlerine ihtiyacınız var',
    approvals: 'Onaylar',
    auditLogs: 'Denetim Kayıtları',
    reservations: 'Rezervasyonlar',
    canceled: 'İptal Edildi',
    released: 'Serbest Bırakıldı',
    
    // Dashboard Quick Actions - Accounting Role
    receiveGoodsAction: 'Mal Kabul',
    receiveGoodsDesc: 'Gelen gönderileri işle ve envanteri güncelle',
    goToGoodsReceipt: 'Mal Kabulüne Git',
    manageReservationsAction: 'Rezervasyonları Yönet',
    manageReservationsDesc: 'Stok rezervasyonlarını görüntüle ve yönet',
    goToReservations: 'Rezervasyonlara Git',
    trackIncomingStockAction: 'Yoldaki Envanteri Takip Et',
    trackIncomingStockDesc: 'Beklenen gönderileri ve teslimatları izle',
    goToIncomingStock: 'Yoldaki Envantere Git',
    
    // Dashboard Quick Actions - Senior Manager Role
    viewIncomingStockAction: 'Yoldaki Envanteri Görüntüle',
    viewIncomingStockDesc: 'Beklenen envanter gönderilerini incele',
    
    // Dashboard Quick Actions - Admin Role
    manageSuppliers: 'Tedarikçileri Yönet',
    addEditManageSupplier: 'Tedarikçi bilgilerini ekle, düzenle ve yönet',
    goToSuppliers: 'Tedarikçilere Git',
    deleteLots: 'Lotları Sil',
    removeLotsFromSystem: 'Lotları sistemden kaldır',
    goToInventory: 'Envantere Git',
    reprintQrCodes: 'QR Kodlarını Yeniden Yazdır',
    regenerateAndPrintQr: 'Lotlar için QR kodlarını yeniden oluştur ve yazdır',
    
    // Lot Queue
    lotQueueDescription: 'Bekleyen girişler için lot bilgilerini tamamla',
    pendingLots: 'Bekleyen Lotlar',
    allLotsCompleted: 'Tüm lotlar tamamlandı ve envantere taşındı',
    completeLotInfo: 'Lot Bilgilerini Tamamla',
    moveToInventory: 'Envantere Taşı',
    validationError: 'Doğrulama Hatası',
    fillRequiredFields: 'Lütfen tüm gerekli alanları doldurun',
    lotMovedSuccess: 'LOT envantere başarıyla taşındı',
    noPermissionPage: 'Bu sayfaya erişim izniniz yok.',
    selectSupplierPlaceholder: 'Bir tedarikçi seçin',
    invoiceNumberPlaceholder: 'örn., INV-2024-001',
    additionalNotesPlaceholder: 'Ek notlar...',
    pendingBadge: 'Beklemede',
    
    // Lot Intake - Single Entry
    newLotEntry: 'Yeni LOT Girişi',
    singleEntryDescription: 'QR kod oluşturma ile tek lot girişi oluşturun',
    intakeSupplier: 'Tedarikçi',
    optionalFields: 'İsteğe Bağlı Alanlar (önerilen)',
    
    // Lot Intake - Bulk Import
    bulkImportInstructions: 'Birden fazla lotu aynı anda içe aktarmak için bir CSV dosyası yükleyin. Doğru format için şablonu indirin.',
    downloadTemplate: 'Şablon İndir',
    importFile: 'Dosyayı İçe Aktar',
    importing: 'İçe Aktarılıyor',
    progress: 'İlerleme',
    importResults: 'İçe Aktarma Sonuçları',
    failed: 'Başarısız',
    errorsFound: 'Hata Bulundu',
    downloadErrorReport: 'Hata Raporunu İndir',
    parsingErrors: 'Ayrıştırma Hataları',
    rowError: 'Satır',
    moreParsingErrors: 'daha fazla ayrıştırma hatası',
    databaseErrors: 'Veritabanı Hataları',
    moreDatabaseErrors: 'daha fazla veritabanı hatası',
    validatingData: 'Veri doğrulanıyor',
    processingFile: 'Dosya işleniyor',
    importStarted: 'İçe aktarma başladı',
    selectFileToImport: 'Lütfen içe aktarılacak bir dosya seçin',
    importError: 'İçe Aktarma Hatası',
    validationFailed: 'Doğrulama Başarısız',
    errorsFoundInFile: 'dosyada hata bulundu',
    
    // Incoming Bulk Upload Dialog
    bulkUploadIncomingStock: 'Yoldaki Stok Toplu Yükleme',
    uploadExcelCsv: 'Excel/CSV Dosyası Yükle',
    template: 'Şablon',
    upload: 'Yükle',
    items: 'Öğeler',
    invoiceHash: 'Fatura #',
    validStatus: 'Geçerli',
    successParsedItems: 'Dosyadan {count} öğe ayrıştırıldı',
    noValidItems: 'Yüklenecek geçerli öğe yok',
    uploadedSuccessfully: '{count} yoldaki stok girişi başarıyla yüklendi',
    failedToParseFile: 'Dosya ayrıştırılamadı. Lütfen formatı kontrol edin.',
    supplierNotFound: 'Tedarikçi "{name}" sistemde bulunamadı',
    invoiceNumberRequired: 'Fatura numarası gereklidir',
    invalidInvoiceDate: 'Geçersiz fatura tarihi formatı (YYYY-AA-GG kullanın)',
    invalidArrivalDate: 'Geçersiz varış tarihi formatı (YYYY-AA-GG kullanın)',
    qualityRequired: 'Kalite gereklidir',
    colorRequired: 'Renk gereklidir',
    metersMustBePositive: 'Beklenen metraj 0\'dan büyük olmalıdır',
    foundItems: '{total} öğe bulundu: {valid} geçerli, {errors} hatalı',
    
    // Order Queue Page
    orderApprovalQueue: 'Sipariş Onay Kuyruğu',
    pendingApprovals: 'Bekleyen Onaylar',
    pendingUppercase: 'Bekleyen',
    processedUppercase: 'İşlendi',
    noOrdersPendingApproval: 'Onay bekleyen sipariş yok',
    orderHash: 'Sipariş #',
    review: 'İncele',
    orderDetails: 'Sipariş Detayları',
    customerLabel: 'Müşteri',
    submittedAtLabel: 'Gönderilme Zamanı',
    orderLots: 'Sipariş Lotları',
    ageDays: 'Yaş (gün)',
    rejectionReasonOptional: 'Reddetme Nedeni (isteğe bağlı)',
    enterReasonForRejection: 'Reddetme nedenini girin...',
    recentlyProcessed: 'Son İşlenenler',
    rejectionReasonTitle: 'Reddetme Nedeni',
    orderApprovedSuccessfully: 'Sipariş başarıyla onaylandı',
    orderRejected: 'Sipariş reddedildi',
    failedToProcessApproval: 'Onay işlenemedi',
    noPermissionOrderQueue: 'Sipariş kuyruğuna erişim izniniz yok. Yöneticinizle iletişime geçin.',
    
    // Approval Queue - Field Changes
    fieldChanges: 'Alan Değişiklikleri',
    pendingFieldChanges: 'Bekleyen Alan Değişiklikleri',
    noPendingFieldChanges: 'Bekleyen alan değişikliği yok',
    field: 'Alan',
    from: 'Önceki Değer',
    to: 'Yeni Değer',
    table: 'Tablo',
    fieldChangeApproved: '{field} için alan değişikliği onaylandı',
    fieldChangeRejected: '{field} için alan değişikliği reddedildi',
    
    // Supplier Management Page
    supplierManagement: 'Tedarikçi Yönetimi',
    totalSuppliers: 'Toplam Tedarikçi',
    activeSuppliersInSystem: 'Sistemdeki aktif tedarikçiler',
    noSuppliersFound: 'Tedarikçi bulunamadı. Başlamak için ilk tedarikçinizi ekleyin.',
    addNewSupplier: 'Yeni Tedarikçi Ekle',
    supplierNameLabel: 'Tedarikçi Adı',
    enterSupplierName: 'Tedarikçi adını girin',
    supplierNameRequired: 'Tedarikçi adı gereklidir.',
    supplierUpdatedSuccessfully: 'Tedarikçi başarıyla güncellendi.',
    supplierCreatedSuccessfully: 'Tedarikçi başarıyla oluşturuldu.',
    failedToSaveSupplier: 'Tedarikçi kaydedilemedi.',
    confirmDeleteSupplier: 'Bu tedarikçiyi silmek istediğinizden emin misiniz?',
    supplierDeletedSuccessfully: 'Tedarikçi başarıyla silindi.',
    failedToDeleteSupplier: 'Tedarikçi silinemedi. Mevcut lotlarla ilişkili olabilir.',
    notAuthorizedSuppliers: 'Tedarikçilere erişim yetkiniz yok.',
    
    // Lot Intake - Additional
    singleLotEntry: 'Tek LOT Girişi',
    bulkLotImport: 'Toplu LOT İçe Aktarma',
    rollCount: 'Top Sayısı',
    invoiceDate: 'Fatura Tarihi',
    productionDate: 'Üretim Tarihi',
    
    // Admin Panel - Additional Keys
    fullName: 'Ad Soyad',
    addNewUser: 'Yeni Kullanıcı Ekle',
    
    // Role Labels (for PermissionsTab and Admin)
    roleWarehouseStaff: 'Depo Personeli',
    roleDescWarehouseStaff: 'Envanter, QR kodları ve sipariş karşılamayı yönetir',
    roleAccounting: 'Muhasebe',
    roleDescAccounting: 'Siparişleri, yoldaki stoğu ve rezervasyonları yönetir',
    roleSeniorManager: 'Kıdemli Yönetici',
    roleDescSeniorManager: 'Değişiklikleri onaylar ve raporlara erişir',
    roleAdmin: 'Yönetici',
    roleDescAdmin: 'Tam sistem erişimi ve kullanıcı yönetimi',
    
    // Admin Panel - User Management
    adminPanel: 'Yönetim Paneli',
    addUser: 'Kullanıcı Ekle',
    activeSystemUsers: 'Aktif sistem kullanıcıları',
    admins: 'Yöneticiler',
    administratorAccounts: 'Yönetici hesapları',
    seniorManagers: 'Kıdemli Yöneticiler',
    seniorManagersDesc: 'Yönetim seviyesi kullanıcılar',
    accounting: 'Muhasebe',
    accountingUsers: 'Muhasebe kullanıcıları',
    warehouseStaff: 'Depo Personeli',
    warehousePersonnel: 'Depo personeli',
    inviteNewUsers: 'Yeni Kullanıcıları Davet Et',
    sendInvitationsToNewMembers: 'Yeni ekip üyelerine davet gönderin',
    reconcilingUsers: 'Uzlaştırılıyor...',
    reconcileUsers: 'Kullanıcıları Uzlaştır',
    enterEmailAddress: 'E-posta adresini girin',
    sending: 'Gönderiliyor...',
    pendingInvitations: 'Bekleyen Davetler',
    usersInvitedNotAccepted: 'Davet edilmiş ancak henüz kabul etmemiş kullanıcılar',
    noPendingInvitations: 'Bekleyen davet yok',
    emailStatus: 'E-posta Durumu',
    invited: 'Davet Edildi',
    emailSentSuccessfully: 'E-posta başarıyla gönderildi',
    provideEmailAndRole: 'Lütfen e-posta ve rol sağlayın',
    invalidEmail: 'Geçersiz E-posta',
    enterValidEmail: 'Lütfen geçerli bir e-posta adresi girin',
    userAlreadyExists: 'Kullanıcı Zaten Mevcut',
    emailAlreadyRegistered: 'Bu e-posta zaten kayıtlı. Bunun yerine mevcut kullanıcıyı düzenleyin.',
    invitationSentSuccessfully: 'Davet e-posta ile başarıyla gönderildi',
    invitationDeleted: '{email} için davet silindi',
    failedToDeleteInvitation: 'Davet silinemedi',
    errorFetchingProfiles: 'Kullanıcı profilleri alınamadı',
    profileUpdatedSuccessfully: 'Profil başarıyla güncellendi',
    failedToUpdateProfile: 'Profil güncellenemedi',
    userDeletedSuccessfully: 'Kullanıcı {name} başarıyla silindi',
    failedToDeleteUser: 'Kullanıcı silinemedi',
    passwordsDoNotMatch: 'Şifreler eşleşmiyor',
    passwordMustBe8Chars: 'Şifre en az 8 karakter uzunluğunda olmalıdır',
    passwordChangedSuccessfully: 'Şifre başarıyla değiştirildi',
    failedToChangePassword: 'Şifre değiştirilemedi',
    passwordTooWeak: 'Şifre çok zayıf. Lütfen daha güçlü bir şifre kullanın.',
    passwordCompromised: 'Bu şifre veri ihlallerinde görünmüş. Lütfen farklı bir tane kullanın.',
    reconciliationComplete: 'Uzlaştırma Tamamlandı',
    reconciliationFailed: 'Uzlaştırma Başarısız',
    invitationResent: 'Davet Yeniden Gönderildi',
    invitationResentTo: '{email} adresine davet yeniden gönderildi',
    resendFailed: 'Yeniden Gönderme Başarısız',
    failedToResendInvitation: 'Davet yeniden gönderilemedi',
    copied: 'Kopyalandı',
    invitationLinkCopied: 'Davet bağlantısı panoya kopyalandı',
    notAuthorizedAccess: 'Bu sayfaya erişim yetkiniz yok',
    
    // Permissions Tab
    permissionsTitle: 'Rol İzinleri Matrisi',
    resetToDefaults: 'Varsayılana Sıfırla',
    saving: 'Kaydediliyor...',
    permissionsUpdatedSuccessfully: 'İzinler başarıyla güncellendi',
    failedToSavePermissions: 'İzinler kaydedilemedi',
    failedToLoadPermissions: 'İzinler yüklenemedi',
    tableHeaderAction: 'İşlem',
    tableHeaderWarehouseStaff: 'Depo Personeli',
    tableHeaderAccounting: 'Muhasebe',
    tableHeaderSeniorManager: 'Kıdemli Yönetici',
    tableHeaderAdmin: 'Yönetici',
    
    // Categories
    categoryUserManagement: 'Kullanıcı Yönetimi',
    categoryInventory: 'Envanter Yönetimi',
    categoryOrders: 'Sipariş Yönetimi',
    categorySuppliers: 'Tedarikçi Yönetimi',
    categoryReports: 'Raporlama ve Analitik',
    categoryQrDocuments: 'QR Kod ve Belge Yönetimi',
    categoryApprovals: 'Onaylar (Değişiklik Talepleri)',
    categoryAuditLogs: 'Denetim Kayıtları',
    
    // User Management Actions
    actionViewUsers: 'Kullanıcıları Görüntüle',
    actionCreateUsers: 'Kullanıcı Oluştur',
    actionEditUsers: 'Kullanıcıları Düzenle',
    actionDeleteUsers: 'Kullanıcıları Sil',
    actionManageRoles: 'Rolleri Yönet',
    actionChangePermissions: 'İzinleri Değiştir',
    
    // Inventory Actions
    actionCreateLotEntries: 'LOT Girişleri Oluştur',
    actionViewInventory: 'Envanteri Görüntüle',
    actionEditLotInfo: 'LOT Bilgilerini Düzenle',
    actionDeleteLotEntries: 'LOT Girişlerini Sil',
    actionGenerateQrCodes: 'QR Kodları Oluştur',
    
    // Order Actions
    actionViewOrders: 'Siparişleri Görüntüle',
    actionCreateOrders: 'Sipariş Oluştur',
    actionEditOrders: 'Siparişleri Düzenle',
    actionDeleteOrders: 'Siparişleri Sil',
    actionFulfillOrders: 'Siparişleri Teslim Et',
    actionPrintOrderDocs: 'Sipariş Belgelerini Yazdır',
    
    // Supplier Actions
    actionViewSuppliers: 'Tedarikçileri Görüntüle',
    actionCreateSuppliers: 'Tedarikçi Oluştur',
    actionEditSuppliers: 'Tedarikçileri Düzenle',
    actionDeleteSuppliers: 'Tedarikçileri Sil',
    
    // Reports Actions
    actionViewReports: 'Raporları Görüntüle',
    actionExportReports: 'Raporları Dışa Aktar',
    actionAccessDashboard: 'Panoya Eriş',
    
    // QR & Documents Actions
    actionScanQrCodes: 'QR Kodlarını Tara',
    actionPrintLotLabels: 'LOT Etiketlerini Yazdır',
    actionBulkQrGeneration: 'Toplu QR Oluşturma',
    
    // Approvals Actions
    actionViewApprovals: 'Onayları Görüntüle',
    actionApproveChanges: 'Değişiklikleri Onayla',
    actionRejectChanges: 'Değişiklikleri Reddet',
    
    // Audit Logs Actions
    actionViewOwnLogs: 'Kendi Kayıtlarını Görüntüle',
    actionViewAllLogs: 'Tüm Kayıtları Görüntüle',
    actionReverseActions: 'İşlemleri Geri Al',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'tr'>('en');

  const t = (key: string): string | string[] => {
    const translation = translations[language][key];
    
    // Missing key detection
    if (translation === undefined) {
      if (process.env.NODE_ENV === 'development') {
        console.warn('[i18n] Missing translation key:', key);
      }
      return `{{missing:${key}}}`;
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
