name: WMS Session 1.2 Webhook Test

on:
  workflow_dispatch:

jobs:
  send_signed_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send signed webhook to WMS receiver
        env:
          WMS_RECEIVER_URL: ${{ secrets.WMS_RECEIVER_URL }}
          WMS_CRM_HMAC_SECRET: ${{ secrets.WMS_CRM_HMAC_SECRET }}
        run: |
          set -euo pipefail

          if [ -z "${WMS_RECEIVER_URL}" ]; then
            echo "Missing secret: WMS_RECEIVER_URL"
            exit 1
          fi

          if [ -z "${WMS_CRM_HMAC_SECRET}" ]; then
            echo "Missing secret: WMS_CRM_HMAC_SECRET"
            exit 1
          fi

          TS=$(date +%s)

          # Keep BODY stable: signature depends on exact bytes.
          BODY='{"event_type":"reservation.created","idempotency_key":"crm:reservation:GH-ACTION-001:created:v1","crm_organization_id":"00000000-0000-0000-0000-000000000000","crm_customer_id":"00000000-0000-0000-0000-000000000000","customer_name":"GitHub Action Test","reserved_date":"2026-02-03","lines":[{"quality_code":"V1001","color_code":"BLACK","uom":"MT","qty":10}]}'

          CANON="${TS}.${BODY}"

          SIG=$(printf "%s" "$CANON" | openssl dgst -sha256 -hmac "$WMS_CRM_HMAC_SECRET" -hex | sed 's/^.* //')

          echo "Timestamp: $TS"
          echo "Signature (hex): $SIG"
          echo "POST -> ${WMS_RECEIVER_URL}"

          curl -i -sS -X POST "$WMS_RECEIVER_URL" \
            -H "Content-Type: application/json" \
            -H "X-WMS-Timestamp: $TS" \
            -H "X-WMS-Signature: $SIG" \
            --data "$BODY"
