// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwcwbyfzzordqwudixvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3Y3dieWZ6em9yZHF3dWRpeHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDY2MTksImV4cCI6MjA3MTY4MjYxOX0.toD6pqqb2w1YBa7LQSWLXb0WI9_6wsGJFLsnSm_BPNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});